// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package asyncserviceconsumer.actions;

import java.util.LinkedHashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class WorkflowTask_CallAsyncTaskStarter extends UserAction<java.lang.Void>
{
	/** @deprecated use WorkflowUserTask.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __WorkflowUserTask;
	private final system.proxies.WorkflowUserTask WorkflowUserTask;
	private final IMendixObject AsyncTaskInput;
	private final java.lang.String PostActionMicroflow;
	private final java.lang.String User;
	private final java.lang.String Password;
	private final java.lang.Boolean isCalledback;

	public WorkflowTask_CallAsyncTaskStarter(
		IContext context,
		IMendixObject _workflowUserTask,
		IMendixObject _asyncTaskInput,
		java.lang.String _postActionMicroflow,
		java.lang.String _user,
		java.lang.String _password,
		java.lang.Boolean _isCalledback
	)
	{
		super(context);
		this.__WorkflowUserTask = _workflowUserTask;
		this.WorkflowUserTask = _workflowUserTask == null ? null : system.proxies.WorkflowUserTask.initialize(getContext(), _workflowUserTask);
		this.AsyncTaskInput = _asyncTaskInput;
		this.PostActionMicroflow = _postActionMicroflow;
		this.User = _user;
		this.Password = _password;
		this.isCalledback = _isCalledback;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE

		Map<String, Object> params = new LinkedHashMap<String, Object>();
		
		String microflowName = "AsyncServiceConsumer.WorkflowTask_CallAsyncTaskStarter_mf";
		String URL_starter_Root;
		
		try {
			URL_starter_Root = AsyncTaskInput.getValue(getContext(), "_SelfStarterUrl");		
		} catch(Exception e)  {  
            System.out.println(e); 
            System.out.println("The entity you submitted misses the \"_SelfStarterUrl\" attribute"); 
            throw new com.mendix.systemwideinterfaces.MendixRuntimeException("The entity you submitted misses the \\\"_SelfStarterUrl\\\" attribute");
        }  
		
		//String AsyncTaskInputId = Long.toString(AsyncTaskInput.getId().toLong());
		String AsyncTaskInputId = AsyncTaskInput.getValue(getContext(), "_TaskInputId");
		String URL_StatusCheck = AsyncTaskInput.getValue(getContext(), "_SelfStatusCheck");
		
		params.put("AsyncTaskInputId", AsyncTaskInputId);
		params.put("URL_starter_Root", URL_starter_Root);
		params.put("URL_StatusCheck", URL_StatusCheck);
		
		params.put("WorkflowUserTask", __WorkflowUserTask);
		params.put("User", User);
		params.put("Password", Password);
		params.put("PostActionMicroflowName", PostActionMicroflow);
		params.put("isCalledback", isCalledback);
		


		

		return Core.microflowCall(microflowName).withParams(params).execute(getContext());
		
		
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "WorkflowTask_CallAsyncTaskStarter";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
