# Relative Path to the script to call, example :
# NX_TopoOptim\1_processor.bat
# -----------------------------------
BatchService1\1_Processor.bat
# NX_TopoOptim\1_processor.bat
# NX_TopoOptim\1_processor_cloud.bat
# Printer3D\1_processor.bat
# Printer3D\1_processor_cloud.bat
