// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JavaScript_SwitchTab(tabId) {
	// BEGIN USER CODE
            // 모든 탭 내용 숨김
            document.querySelectorAll('.tab-content').forEach(content => {
                content.classList.remove('active');
            });
            
            // 모든 탭 버튼 비활성화
            document.querySelectorAll('.tab-button').forEach(button => {
                button.classList.remove('active');
            });
            
            // 선택된 탭 활성화
            document.getElementById(tabId).classList.add('active');
            event.target.classList.add('active');
            
            // 진행률 업데이트
            const tabs = ['basic', 'process', 'system', 'schedule', 'organization'];
            const currentIndex = tabs.indexOf(tabId);
            const progress = ((currentIndex + 1) / tabs.length) * 100;
            document.getElementById('progressBar').style.width = progress + '%';
        
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
