// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package forgotpassword.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class GenerateURL extends UserAction<java.lang.String>
{
	private final java.lang.String UUID;
	private final java.lang.String AppRootURL;
	private final java.lang.String URLPrefix;

	public GenerateURL(
		IContext context,
		java.lang.String _uUID,
		java.lang.String _appRootURL,
		java.lang.String _uRLPrefix
	)
	{
		super(context);
		this.UUID = _uUID;
		this.AppRootURL = _appRootURL;
		this.URLPrefix = _uRLPrefix;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String url = AppRootURL;	
		if( !url.endsWith("/") )
			url += "/";
		    url = String.format("%s%s/ForgotPassword/%s",url,this.URLPrefix,this.UUID);

		return url;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateURL";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
