// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package forgotpassword.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import forgotpassword.implementation.handlers.SignInHandler;

public class InitializeRequestHandler extends UserAction<java.lang.Void>
{
	public InitializeRequestHandler(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		initializeHandler(getContext());
        return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitializeRequestHandler";
	}

	// BEGIN EXTRA CODE

    private static boolean handlerStarted = false;

    protected static void initializeHandler(IContext context)
    {
        if( !handlerStarted ) {
            Core.addRequestHandler("signin/", new SignInHandler(context));
            handlerStarted = true;
        }
    }
	// END EXTRA CODE
}
