// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package forgotpassword.actions;

import java.util.Calendar;
import java.util.UUID;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class SignIn extends UserAction<IMendixObject>
{
	/** @deprecated use UserAccount.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __UserAccount;
	private final system.proxies.User UserAccount;
	private final java.lang.Long ExpireInSeconds;

	public SignIn(
		IContext context,
		IMendixObject _userAccount,
		java.lang.Long _expireInSeconds
	)
	{
		super(context);
		this.__UserAccount = _userAccount;
		this.UserAccount = _userAccount == null ? null : system.proxies.User.initialize(getContext(), _userAccount);
		this.ExpireInSeconds = _expireInSeconds;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

        InitializeRequestHandler.initializeHandler(getContext());
        forgotpassword.proxies.AuthResetTemp signIn = forgotpassword.proxies.AuthResetTemp.initialize(getContext(), Core.instantiate(getContext(), forgotpassword.proxies.AuthResetTemp.entityName));
		
		String uuid = UUID.randomUUID().toString();
        signIn.setUUID(uuid);
        signIn.setUsername(this.UserAccount.getName());
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.add(Calendar.SECOND, Math.toIntExact(ExpireInSeconds));
        signIn.setExpiryDate(cal.getTime());

        Core.commit(getContext(), signIn.getMendixObject());

		return signIn.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SignIn";
	}

	// BEGIN EXTRA CODE

	// END EXTRA CODE
}
