// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdfformeditor.actions;

import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.timeseries.mendix.pdfeditor.service.PdfService;
import com.timeseries.mendix.pdfeditor.dto.ErrorDto;
import org.apache.pdfbox.pdmodel.PDDocument;
import pdfformeditor.proxies.ErrorNP;
import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_FlattenForm extends UserAction<IMendixObject>
{
	/** @deprecated use inputDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __inputDocument;
	private final system.proxies.FileDocument inputDocument;
	/** @deprecated use outputDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __outputDocument;
	private final system.proxies.FileDocument outputDocument;

	public JA_FlattenForm(
		IContext context,
		IMendixObject _inputDocument,
		IMendixObject _outputDocument
	)
	{
		super(context);
		this.__inputDocument = _inputDocument;
		this.inputDocument = _inputDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _inputDocument);
		this.__outputDocument = _outputDocument;
		this.outputDocument = _outputDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputDocument);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ErrorNP errorNP = null;
		requireNonNull(inputDocument, "inputDocument is required");
		requireNonNull(outputDocument, "outputDocument is required");
		if (!inputDocument.getHasContents(context())) {
			throw new IllegalArgumentException("The document doesn't have contents");
		}

		try (InputStream fileDocumentContent = Core.getFileDocumentContent(context(), inputDocument.getMendixObject());
		     PdfService pdfService = new PdfService(PDDocument.load(fileDocumentContent))) {
			ErrorDto dto = pdfService.flatten();
			if (dto != null){
				errorNP = JA_UpdateFields.convertErrorFromDto(dto, context());
				return errorNP.getMendixObject();
			}
			else{
				JA_UpdateField.writePdf(pdfService, outputDocument, context());
				return null;
			}
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_FlattenForm";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
