// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdfformeditor.actions;

import java.io.InputStream;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.timeseries.mendix.pdfeditor.service.PdfService;
import org.apache.pdfbox.pdmodel.PDDocument;
import static java.util.Objects.requireNonNull;
import static java.util.stream.Collectors.toList;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_GetFields extends UserAction<java.util.List<IMendixObject>>
{
	/** @deprecated use inputDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __inputDocument;
	private final system.proxies.FileDocument inputDocument;

	public JA_GetFields(
		IContext context,
		IMendixObject _inputDocument
	)
	{
		super(context);
		this.__inputDocument = _inputDocument;
		this.inputDocument = _inputDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _inputDocument);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

		requireNonNull(inputDocument, "inputdocument is required");
		if (!inputDocument.getHasContents(context())) {
			throw new IllegalArgumentException("The document doesn't have contents");
		}

		try (InputStream fileDocumentContent = Core.getFileDocumentContent(context(), inputDocument.getMendixObject());
		     PdfService pdfService = new PdfService(PDDocument.load(fileDocumentContent))) {
			return pdfService.getFields().stream()
					.map(dto -> JA_GetField.convertDtoToField(dto, context()))
					.collect(toList());
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetFields";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
