// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdfformeditor.actions;

import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.timeseries.mendix.pdfeditor.dto.FieldDto;
import com.timeseries.mendix.pdfeditor.service.PdfService;
import org.apache.pdfbox.pdmodel.PDDocument;
import pdfformeditor.proxies.ENUM_PdfFieldType;
import pdfformeditor.proxies.Field;
import pdfformeditor.proxies.PossibleValue;
import static java.util.Objects.requireNonNull;
import static java.util.stream.Collectors.toList;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_GetField extends UserAction<IMendixObject>
{
	/** @deprecated use inputDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __inputDocument;
	private final system.proxies.FileDocument inputDocument;
	private final java.lang.String fullyQualifiedName;

	public JA_GetField(
		IContext context,
		IMendixObject _inputDocument,
		java.lang.String _fullyQualifiedName
	)
	{
		super(context);
		this.__inputDocument = _inputDocument;
		this.inputDocument = _inputDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _inputDocument);
		this.fullyQualifiedName = _fullyQualifiedName;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		requireNonNull(inputDocument, "inputdocument is required");
		requireNonNull(fullyQualifiedName, "fullyQualifiedName is required");
		if (!inputDocument.getHasContents(context())) {
			throw new IllegalArgumentException("The document doesn't have contents");
		}

		try (InputStream fileDocumentContent = Core.getFileDocumentContent(context(), inputDocument.getMendixObject());
		     PdfService pdfService = new PdfService(PDDocument.load(fileDocumentContent))) {
			return pdfService.getField(fullyQualifiedName)
					.map(dto -> convertDtoToField(dto, context()))
					.orElse(null);
		}


		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetField";
	}

	// BEGIN EXTRA CODE

	public static IMendixObject convertDtoToField(FieldDto dto, IContext context) {
		Field mxField = new Field(context);
		mxField.setFullyQualifiedName(dto.getFullyQualifiedName());
		mxField.setPartialName(dto.getPartialName());
		mxField.setAlternateFieldName(dto.getAlternateFieldName());
		mxField.setMappingName(dto.getMappingName());
		mxField.setValue(dto.getValue());
		mxField.setFieldType(ENUM_PdfFieldType.valueOf(dto.getType().toString()));
		mxField.setField_PossibleValue(dto.getPossibleValues().stream().map(
				s -> {
					PossibleValue possibleValue = new PossibleValue(context);
					possibleValue.setValue(s);
					return possibleValue;
				}).collect(toList()));
		mxField.setIsReadOnly(dto.isReadOnly());
		mxField.setIsRequired(dto.isRequired());
		return mxField.getMendixObject();

	}

	// END EXTRA CODE
}
