// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pdfformeditor.actions;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.timeseries.mendix.pdfeditor.dto.ErrorDto;
import com.timeseries.mendix.pdfeditor.service.PdfService;
import org.apache.pdfbox.pdmodel.PDDocument;
import pdfformeditor.proxies.ErrorNP;
import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_UpdateField extends UserAction<IMendixObject>
{
	/** @deprecated use inputDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __inputDocument;
	private final system.proxies.FileDocument inputDocument;
	/** @deprecated use outputDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __outputDocument;
	private final system.proxies.FileDocument outputDocument;
	private final java.lang.String fullyQualifiedName;
	private final java.lang.String value;
	private final java.lang.Boolean flattenForm;

	public JA_UpdateField(
		IContext context,
		IMendixObject _inputDocument,
		IMendixObject _outputDocument,
		java.lang.String _fullyQualifiedName,
		java.lang.String _value,
		java.lang.Boolean _flattenForm
	)
	{
		super(context);
		this.__inputDocument = _inputDocument;
		this.inputDocument = _inputDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _inputDocument);
		this.__outputDocument = _outputDocument;
		this.outputDocument = _outputDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputDocument);
		this.fullyQualifiedName = _fullyQualifiedName;
		this.value = _value;
		this.flattenForm = _flattenForm;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ErrorNP errorNP = null;
		requireNonNull(inputDocument, "inputDocument is required");
		requireNonNull(outputDocument, "outputDocument is required");
		requireNonNull(fullyQualifiedName, "fullyQualifiedName is required");
		if (!inputDocument.getHasContents(context())) {
			throw new IllegalArgumentException("The document doesn't have contents");
		}

		try (InputStream fileDocumentContent = Core.getFileDocumentContent(context(), inputDocument.getMendixObject()); 
		    PdfService pdfService = new PdfService(PDDocument.load(fileDocumentContent))) {
			ErrorDto dto = pdfService.updateField(fullyQualifiedName, value, flattenForm);
			if (dto != null){
				errorNP = JA_UpdateFields.convertErrorFromDto(dto, context());
				return errorNP.getMendixObject();
			}
			else{
				writePdf(pdfService, outputDocument, context());
				return null;
			}
		}


		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_UpdateField";
	}

	// BEGIN EXTRA CODE

	public static void writePdf(PdfService pdfService, system.proxies.FileDocument outputDocument, IContext context) throws IOException {
		ByteArrayOutputStream os = new ByteArrayOutputStream();
		pdfService.writePDF(os);
		Core.storeFileDocumentContent(context, outputDocument.getMendixObject(), new ByteArrayInputStream(os.toByteArray()));
	}

	// END EXTRA CODE
}
