@echo off
call %~dp0.\TaskEnv.bat

REM This script template will be copied in the task dir and then the result script will be executed from there
REM the result script can be rerun because there's no environment inherited, it's convenient for debug purpose
REM The task environement variables will be (re)loaded by this script "TaskEnv.bat" which was generated by the Processor script
REM TaskEnv.bat sets : MendixAppRootURL, TaskDir, ParamFileLocation, JQ_cmd, ProcessorUid, ProcessorDir,AsyncTaskID,TaskJsonFile,TaskInputFile,TaskOutputFile

REM All the response is expected in TaskOutputFile in the JSON format expected by the service. If the response includes files, they should be encoded in Base64 and included in TaskOutputFile as strings.

REM =============================  Custom Code START  ==============================================
	REM   SETTINGS 



	REM   PARAMETERS 
		REM setlocal EnableDelayedExpansion 


	REM  START 
		echo.
		echo.
		echo EXECUTE TASK
		echo.
		echo   JQ_cmd              : "%JQ_cmd%"
		echo   ProcessorUid        : "%ProcessorUid%"
		echo   ProcessorDir        : "%ProcessorDir%"
		echo   ServiceName         : "%ServiceName%"
		echo.
		echo   AsyncTaskID         : "%AsyncTaskID%"
		echo   TaskDir             : "%TaskDir%"
		echo   TaskJsonFile        : "%TaskJsonFileLocation%"
		echo   TaskInputFile       : "%TaskInputFile%"
		echo   TaskOutputFile      : "%TaskOutputFile%"
		echo.
		

	REM  EXTRACT metadata  from REQUEST 
		REM For /F "Delims=" %%G in ('%JQ_cmd% .Longueur ^< "%TaskInputFile%"')             Do ( Set Longueur=%%G)
		REM For /F "Delims=" %%G in ('%JQ_cmd% .Largeur ^< "%TaskInputFile%"')              Do ( Set Largeur=%%G)
	
	
	REM  EXTRACT files from REQUEST 

		REM Parse files params directly from the file, and put the base64 string directly into a text file (loading it as a variable triggers errors)
		REM set JPG_Path=%TaskDir%\JPG.jpg
		REM set JPG_PathBase64=%JPG_Path%_base64.txt
		REM %JQ_cmd% -r .NxThumbnail.Contents<"%TaskInputFile%">"%JPG_PathBase64%"	
		REM Decode base64 text files to original files
		REM certutil -f -decode "%JPG_PathBase64%" "%JPG_Path%"


	REM  PROCESS 

		set ResultImagePath=%ProcessorDir%\Chatillon.jpg
		
	REM PREPARE RESPONSE FILES (if any) as Base64 string
		REM set related-result-file=%TaskDir%\FileName.jpg
		REM set related-result-file=%related-result-file:"=%
		REM set related-result-file-Base64=%related-result-file%_Base64.txt
		REM CertUtil -encodehex -f "%related-result-file%" "%related-result-file-Base64%" 1
		REM set /p related-result-as-string=<"%related-result-file-Base64%"
		
	REM BUILD RESPONSE in TaskOutputFile file is the Json format expected by the service, with related files as Base64 strings 
		set JSON_response={"Attribute1":"Value1","Attribute2":"Value2"}
		echo %JSON_response%>"%TaskOutputFile%"


REM =============================  Custom Code END    ==============================================

REM  PUBLISH TaskOutputFile as Response 	
	call %ProcessorDir%\..\bin\PublishTaskResult.bat
	echo.
	REM rd /S /Q "%TaskDir%"
