// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixavalidator.actions;

import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.FeedbackHelper;
import emixavalidator.proxies.Enum_ValidationType;
import emixavalidator.proxies.Validation;
import emixavalidator.proxies.constants.Constants;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class AddCustomValidation extends UserAction<java.lang.Boolean>
{
	/** @deprecated use ValidatorObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ValidatorObject;
	private final emixavalidator.proxies.Validator ValidatorObject;
	private final emixavalidator.proxies.Enum_ValidationType ValidationType;
	private final IMendixObject ObjectToValidate;
	private final java.lang.String AttributeToValidate;
	private final java.lang.String MessageCode;
	private final java.lang.String MessageType;
	private final java.lang.String ValidationMessage;
	private final java.lang.Long RemoteGUID;
	private final java.math.BigDecimal CustomDecimal;
	private final java.lang.Long CustomLong;
	private final java.util.Date CustomDate;
	private final java.lang.String CustomString;

	public AddCustomValidation(
		IContext context,
		IMendixObject _validatorObject,
		java.lang.String _validationType,
		IMendixObject _objectToValidate,
		java.lang.String _attributeToValidate,
		java.lang.String _messageCode,
		java.lang.String _messageType,
		java.lang.String _validationMessage,
		java.lang.Long _remoteGUID,
		java.math.BigDecimal _customDecimal,
		java.lang.Long _customLong,
		java.util.Date _customDate,
		java.lang.String _customString
	)
	{
		super(context);
		this.__ValidatorObject = _validatorObject;
		this.ValidatorObject = _validatorObject == null ? null : emixavalidator.proxies.Validator.initialize(getContext(), _validatorObject);
		this.ValidationType = _validationType == null ? null : emixavalidator.proxies.Enum_ValidationType.valueOf(_validationType);
		this.ObjectToValidate = _objectToValidate;
		this.AttributeToValidate = _attributeToValidate;
		this.MessageCode = _messageCode;
		this.MessageType = _messageType;
		this.ValidationMessage = _validationMessage;
		this.RemoteGUID = _remoteGUID;
		this.CustomDecimal = _customDecimal;
		this.CustomLong = _customLong;
		this.CustomDate = _customDate;
		this.CustomString = _customString;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.ValidatorObject == null || this.ObjectToValidate == null || this.ValidationType == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Not all the required import parameters are set.");
		}
		
		String AttributeToValidateString = ""; //Allows validations to be added to empty attributes
		if (this.AttributeToValidate != null) {
			AttributeToValidateString = this.AttributeToValidate;
		}
		
		String msgCode = (MessageCode != null) ? MessageCode : "";
		String msgType = (MessageType != null) ? MessageType : "";
		
		IContext context = this.getContext();		
		Validation newValidation = new Validation(context);
		IMetaObject objectMeta = this.ObjectToValidate.getMetaObject();
		String moduleName = objectMeta.getModuleName();
		String objectName = objectMeta.getName().replace(moduleName + ".", "");
		
		Map<String, ? extends IMendixObjectMember<?>> memberList = this.ObjectToValidate.getMembers(context);
		IMendixObjectMember<?> objectMember = memberList.get(this.AttributeToValidate);
		
		if(objectMember == null && AttributeToValidateString != ""){
			String validationType = this.ValidationType.getCaption();
			String errorMessage = "Attribute: '" + this.AttributeToValidate + "' is not a valid member." + System.lineSeparator() + "Failed to validate with the message below: " + System.lineSeparator() + System.lineSeparator() + this.ValidationMessage; 
			String logMessage = "A validation of type: " + validationType + " was added to Attribute: '" + this.AttributeToValidate + "' This attribute is not a member of Object: '" + objectName + "'. Validation not added.";
			Core.getLogger(Constants.getLogNode()).error(logMessage);
			FeedbackHelper.addTextMessageFeedback(context, com.mendix.systemwideinterfaces.core.IFeedback.MessageType.WARNING, errorMessage, true);
			ValidatorObject.setIsValid(false);
		} else{
			//Making sure the message fits. Trim excess if needed
			String valMessage = this.ValidationMessage.length() > 2000 ? this.ValidationMessage.substring(0, 1997) + "..." : this.ValidationMessage;
			newValidation.setValidation_Validator(context, this.ValidatorObject);
			newValidation.setValidationType(this.ValidationType);
			newValidation.set_ObjectToValidateUUID(this.ObjectToValidate.getId().toLong());
			newValidation.setObjectName(context, objectName);
			newValidation.setAttributeToValidate(AttributeToValidateString);
			newValidation.setMessageCode(msgCode);
			newValidation.setMessageType(msgType);
			newValidation.setMessage(valMessage);
			newValidation.setRemoteGUID(this.RemoteGUID);
			newValidation.setCustomDecimal(this.CustomDecimal);
			newValidation.setCustomLong(this.CustomLong);
			newValidation.setCustomDate(this.CustomDate);
			newValidation.setCustomString(this.CustomString);
			if(this.ValidationType == Enum_ValidationType.Error){
				ValidatorObject.setIsValid(false);
			}
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddCustomValidation";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
