// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixavalidator.actions;

import java.util.Map;
import emixavalidator.proxies.constants.Constants;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import emixavalidator.proxies.Enum_ValidationType;
import emixavalidator.proxies.Validation;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.webui.FeedbackHelper;
import com.mendix.systemwideinterfaces.core.IFeedback.MessageType;
import com.mendix.systemwideinterfaces.core.UserAction;

public class AddValidation extends UserAction<java.lang.Boolean>
{
	/** @deprecated use ValidatorObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ValidatorObject;
	private final emixavalidator.proxies.Validator ValidatorObject;
	private final emixavalidator.proxies.Enum_ValidationType ValidationType;
	private final IMendixObject ObjectToValidate;
	private final java.lang.String AttributeToValidate;
	private final java.lang.String MessageCode;
	private final java.lang.String ValidationMessage;

	public AddValidation(
		IContext context,
		IMendixObject _validatorObject,
		java.lang.String _validationType,
		IMendixObject _objectToValidate,
		java.lang.String _attributeToValidate,
		java.lang.String _messageCode,
		java.lang.String _validationMessage
	)
	{
		super(context);
		this.__ValidatorObject = _validatorObject;
		this.ValidatorObject = _validatorObject == null ? null : emixavalidator.proxies.Validator.initialize(getContext(), _validatorObject);
		this.ValidationType = _validationType == null ? null : emixavalidator.proxies.Enum_ValidationType.valueOf(_validationType);
		this.ObjectToValidate = _objectToValidate;
		this.AttributeToValidate = _attributeToValidate;
		this.MessageCode = _messageCode;
		this.ValidationMessage = _validationMessage;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.ValidatorObject == null || this.ObjectToValidate == null || this.ValidationType == null) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Not all the required import parameters are set.");
		}
		
		String attributeToValidateString = (AttributeToValidate != null) ? AttributeToValidate : "";
		String msgCode = (MessageCode != null) ? MessageCode : "";
		String validationMsg = (ValidationMessage != null) ? ValidationMessage : "";
		
		IContext context = this.getContext();		
		Validation newValidation = new Validation(context);
		IMetaObject objectMeta = this.ObjectToValidate.getMetaObject();
		String moduleName = objectMeta.getModuleName();
		String objectName = objectMeta.getName().replace(moduleName + ".", "");
		
		Map<String, ? extends IMendixObjectMember<?>> memberList = this.ObjectToValidate.getMembers(context);
		IMendixObjectMember<?> objectMember = memberList.get(this.AttributeToValidate);
		
		if(objectMember == null && attributeToValidateString != ""){
			String validationType = this.ValidationType.getCaption();
			String errorMessage = "Attribute: '" + this.AttributeToValidate + "' is not a valid member." + System.lineSeparator() + "Failed to validate with the message below: " + System.lineSeparator() + System.lineSeparator() + this.ValidationMessage; 
			String logMessage = "A validation of type: " + validationType + " was added to Attribute: '" + this.AttributeToValidate + "' This attribute is not a member of Object: '" + objectName + "'. Validation not added.";
			Core.getLogger(Constants.getLogNode()).error(logMessage);
			FeedbackHelper.addTextMessageFeedback(context, MessageType.WARNING, errorMessage, true);
			ValidatorObject.setIsValid(false);
		} else{
			//Making sure the message fits. Trim excess if needed
			String valMessage = validationMsg.length() > 2000 ? validationMsg.substring(0, 1997) + "..." : validationMsg;
			newValidation.setValidation_Validator(context, this.ValidatorObject);
			newValidation.setValidationType(this.ValidationType);
			newValidation.set_ObjectToValidateUUID(this.ObjectToValidate.getId().toLong());
			newValidation.setObjectName(context, objectName);
			newValidation.setAttributeToValidate(attributeToValidateString);
			newValidation.setMessageCode(msgCode);
			newValidation.setMessage(valMessage);
			if(this.ValidationType == Enum_ValidationType.Error){
				ValidatorObject.setIsValid(false);
			}
		}
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddValidation";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
