// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixavalidator.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import emixavalidator.proxies.Enum_ValidationType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DisplayValidationFeedbackByObject extends UserAction<java.lang.Boolean>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(ValidationsList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __ValidationsList;
	private final java.util.List<emixavalidator.proxies.Validation> ValidationsList;
	private final IMendixObject ObjectWithFeedback;
	/** @deprecated use ValidatorObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ValidatorObject;
	private final emixavalidator.proxies.Validator ValidatorObject;

	public DisplayValidationFeedbackByObject(
		IContext context,
		java.util.List<IMendixObject> _validationsList,
		IMendixObject _objectWithFeedback,
		IMendixObject _validatorObject
	)
	{
		super(context);
		this.__ValidationsList = _validationsList;
		this.ValidationsList = java.util.Optional.ofNullable(_validationsList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(validationsListElement -> emixavalidator.proxies.Validation.initialize(getContext(), validationsListElement))
			.collect(java.util.stream.Collectors.toList());
		this.ObjectWithFeedback = _objectWithFeedback;
		this.__ValidatorObject = _validatorObject;
		this.ValidatorObject = _validatorObject == null ? null : emixavalidator.proxies.Validator.initialize(getContext(), _validatorObject);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> validations = new ArrayList<IMendixObject>();
		
		for (IMendixObject validation : __ValidationsList ) {		
			//if not equal to object name
			if ( !emixavalidator.proxies.Validation.initialize(getContext(), validation).getObjectName().equals(ObjectWithFeedback.getType() )
			 	 && emixavalidator.proxies.Validation.initialize(getContext(), validation).getValidationType()	== Enum_ValidationType.Error )
			{
				validations.add(validation);
				this.ValidatorObject.setValidationErrors(getContext(), true);
			}
		}
		
		
		 return new DisplayValidatorFeedback(getContext(), validations).execute();
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DisplayValidationFeedbackByObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
