// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixavalidator.actions;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.mendix.core.objectmanagement.DataValidationInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import emixavalidator.proxies.Validation;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DisplayValidatorFeedback extends UserAction<java.lang.Boolean>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(validationList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __validationList;
	private final java.util.List<emixavalidator.proxies.Validation> validationList;

	public DisplayValidatorFeedback(
		IContext context,
		java.util.List<IMendixObject> _validationList
	)
	{
		super(context);
		this.__validationList = _validationList;
		this.validationList = java.util.Optional.ofNullable(_validationList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(validationListElement -> emixavalidator.proxies.Validation.initialize(getContext(), validationListElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = this.getContext();
		HashMap<Long, HashMap<String, List<IMendixObject>>> messages = new HashMap<Long, HashMap<String, List<IMendixObject>>>(); 
		
		for(IMendixObject validation : __validationList){
			Validation validationObj = Validation.initialize(context, validation);
			long objectToValidateUUID = validationObj.get_ObjectToValidateUUID();;
			if(objectToValidateUUID == 0){
				throw new com.mendix.systemwideinterfaces.MendixRuntimeException("ObjectToValidate could not be found.");
			}
					
			if(!messages.containsKey(objectToValidateUUID)){
				messages.put(objectToValidateUUID, new HashMap<String, List<IMendixObject>>());
			}
					
			HashMap<String, List<IMendixObject>> messagesPerObject = messages.get(objectToValidateUUID);
			
			if(!messagesPerObject.containsKey(validationObj.getAttributeToValidate())){
				messagesPerObject.put(validationObj.getAttributeToValidate(), new ArrayList<IMendixObject>());
			}
			messagesPerObject.get(validationObj.getAttributeToValidate()).add(validation);
		}
		
		for(Map.Entry<Long, HashMap<String, List<IMendixObject>>> entry : messages.entrySet()){
			Long objectId = entry.getKey();
			if(objectId == 0){
				throw new com.mendix.systemwideinterfaces.MendixRuntimeException("MessageKey could not be found.");
			}
			HashMap<String, List<IMendixObject>> messagePerObject = entry.getValue();
			
			for(Map.Entry<String, List<IMendixObject>> entry2 : messagePerObject.entrySet()){
				List<IMendixObject> messagesPerAttribute = entry2.getValue();
				String totalValidationMessage = "";
				for(IMendixObject validation : messagesPerAttribute){
					Validation message = Validation.initialize(context, validation);
					totalValidationMessage += message.getMessage() + "\r\n";
				}
				
				String attrName = entry2.getKey();
				DataValidationInfo dvi = new DataValidationInfo(objectId);
				dvi.addErrorField(attrName, totalValidationMessage);
				context.addDataValidation(dvi);		
			}
				
		}

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DisplayValidatorFeedback";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
