// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixavalidator.actions;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.mendix.systemwideinterfaces.core.IContext;
import emixavalidator.proxies.Validation;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Returns a JSON formated string with messages, useful for response messages in REST services.
 * Input is a list of Validations and a Boolean to indicated the amount of details you would like to return. 
 */
public class ValidationsToJson extends UserAction<java.lang.String>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(validationList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __validationList;
	private final java.util.List<emixavalidator.proxies.Validation> validationList;
	private final java.lang.Boolean displayDetails;

	public ValidationsToJson(
		IContext context,
		java.util.List<IMendixObject> _validationList,
		java.lang.Boolean _displayDetails
	)
	{
		super(context);
		this.__validationList = _validationList;
		this.validationList = java.util.Optional.ofNullable(_validationList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(validationListElement -> emixavalidator.proxies.Validation.initialize(getContext(), validationListElement))
			.collect(java.util.stream.Collectors.toList());
		this.displayDetails = _displayDetails;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String JSONList = "[]";
		Map<String, List<HashMap<String, String>>> messageList = new HashMap<>();
		for (Validation validation : validationList) {
			String validationTypeString = validation.getValidationType().getCaption();
			HashMap<String, String> message = new HashMap<>();
			if(displayDetails) {
				message.put("code", validation.getMessageCode());
				message.put("object", validation.getObjectName());
			}
			message.put("attribute", validation.getAttributeToValidate());
			message.put("message", validation.getMessage());
			List<HashMap<String, String>> list = new ArrayList<HashMap<String, String>>();
			list.add(message);
			if (messageList.containsKey(validationTypeString)) {
				list.addAll(messageList.get(validationTypeString));
				messageList.put(validationTypeString, list);
			} else {
				messageList.put(validationTypeString, list);
			}
		}
		if(!messageList.isEmpty()) {
	        ObjectMapper objectMapper = new ObjectMapper();
	        JSONList = objectMapper.writeValueAsString(messageList);
		}
		return JSONList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ValidationsToJson";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
