// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import documentgenerationformendix.helpers.StaticFunctions;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Allows for merging documents based on a MergeInput Object, Word template System.FileDoc, OutputDoc Object, an ML DataFile and list of Charts, then returns true or false.
 */
public class AdvancedMergeXML extends UserAction<java.lang.Boolean>
{
	/** @deprecated use mergeInput.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __mergeInput;
	private final documentgenerationformendix.proxies.MergeInput mergeInput;
	/** @deprecated use wordTemplate.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __wordTemplate;
	private final system.proxies.FileDocument wordTemplate;
	/** @deprecated use outputDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __outputDoc;
	private final system.proxies.FileDocument outputDoc;
	/** @deprecated use com.mendix.utils.ListUtils.map(charts, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __charts;
	private final java.util.List<documentgenerationformendix.proxies.Chart> charts;
	/** @deprecated use xMLDataFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __xMLDataFile;
	private final system.proxies.FileDocument xMLDataFile;

	public AdvancedMergeXML(
		IContext context,
		IMendixObject _mergeInput,
		IMendixObject _wordTemplate,
		IMendixObject _outputDoc,
		java.util.List<IMendixObject> _charts,
		IMendixObject _xMLDataFile
	)
	{
		super(context);
		this.__mergeInput = _mergeInput;
		this.mergeInput = _mergeInput == null ? null : documentgenerationformendix.proxies.MergeInput.initialize(getContext(), _mergeInput);
		this.__wordTemplate = _wordTemplate;
		this.wordTemplate = _wordTemplate == null ? null : system.proxies.FileDocument.initialize(getContext(), _wordTemplate);
		this.__outputDoc = _outputDoc;
		this.outputDoc = _outputDoc == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputDoc);
		this.__charts = _charts;
		this.charts = java.util.Optional.ofNullable(_charts)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(chartsElement -> documentgenerationformendix.proxies.Chart.initialize(getContext(), chartsElement))
			.collect(java.util.stream.Collectors.toList());
		this.__xMLDataFile = _xMLDataFile;
		this.xMLDataFile = _xMLDataFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _xMLDataFile);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StaticFunctions.advancedMergeXML(this.getContext(), this.__wordTemplate,  this.__outputDoc, this.mergeInput, this.xMLDataFile);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AdvancedMergeXML";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
