// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import java.io.File;
import java.io.FileInputStream;
import com.aspose.words.License;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import documentgenerationformendix.helpers.StaticFunctions;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Put Aspose license in the resources folder.
 */
public class AposeLicense_ASU extends UserAction<java.lang.Boolean>
{
	public AposeLicense_ASU(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StaticFunctions.activateLicense();		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AposeLicense_ASU";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
