// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.meta.IMetaAssociation;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Association_GetCompleteName extends UserAction<IMendixObject>
{
	private final java.lang.String Association;

	public Association_GetCompleteName(
		IContext context,
		java.lang.String _association
	)
	{
		super(context);
		this.Association = _association;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
        String fullName = null;
        for (IMetaAssociation metaAssociation : Core.getMetaAssociations()) {
            if (metaAssociation.getName().endsWith("." + Association)) {
                fullName = metaAssociation.getName();
                break;
            }
        }

        if (fullName == null) {
            throw new RuntimeException("Association '" + Association + "' not found");
        }

        IMendixObject entity = Core.instantiate(getContext(), "DocumentGenerationForMendix.Entity");
        entity.setValue(getContext(), "AssociationCompleteName", fullName);

        return entity;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Association_GetCompleteName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
