// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import com.aspose.words.Document;
import com.aspose.words.FontSettings;
import com.aspose.words.ImportFormatMode;
import com.aspose.words.SectionStart;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import documentgenerationformendix.helpers.StaticFunctions;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Concat multiple MS Word documents to one. The Table Of Contents will be updated to.
 */
public class concatenateWordDocuments extends UserAction<java.lang.Boolean>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(wordDocuments, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __wordDocuments;
	private final java.util.List<system.proxies.FileDocument> wordDocuments;
	/** @deprecated use outputDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __outputDoc;
	private final system.proxies.FileDocument outputDoc;
	/** @deprecated use mergeInput.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __mergeInput;
	private final documentgenerationformendix.proxies.MergeInput mergeInput;

	public concatenateWordDocuments(
		IContext context,
		java.util.List<IMendixObject> _wordDocuments,
		IMendixObject _outputDoc,
		IMendixObject _mergeInput
	)
	{
		super(context);
		this.__wordDocuments = _wordDocuments;
		this.wordDocuments = java.util.Optional.ofNullable(_wordDocuments)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(wordDocumentsElement -> system.proxies.FileDocument.initialize(getContext(), wordDocumentsElement))
			.collect(java.util.stream.Collectors.toList());
		this.__outputDoc = _outputDoc;
		this.outputDoc = _outputDoc == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputDoc);
		this.__mergeInput = _mergeInput;
		this.mergeInput = _mergeInput == null ? null : documentgenerationformendix.proxies.MergeInput.initialize(getContext(), _mergeInput);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (__wordDocuments == null) {
			throw new IllegalArgumentException("WordDocuments is empty");
		} else if (__wordDocuments.size() < 2) {
			throw new IllegalArgumentException("WordDocuments has less than 2 documents");
		}

		if (outputDoc.getName() == null || outputDoc.getName().trim().isEmpty()) {
			outputDoc.setName("ouput.docx");
	    }
			
		return StaticFunctions.concatenateWordDocuments(this.getContext(), __wordDocuments, __outputDoc, mergeInput);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "concatenateWordDocuments";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
