// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class IsSpecializationOfSystemImage extends UserAction<java.lang.Boolean>
{
	private final java.lang.String entityName;

	public IsSpecializationOfSystemImage(
		IContext context,
		java.lang.String _entityName
	)
	{
		super(context);
		this.entityName = _entityName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        if (entityName == null || entityName.isEmpty()) {
            return false;
        }

        IMetaObject metaObject = Core.getMetaObject(entityName);
        return isSpecializationOfSystemImage(metaObject);
    }

    private boolean isSpecializationOfSystemImage(IMetaObject entity) {
        final String SYSTEM_IMAGE = "System.Image";
        for (IMetaObject currentEntity = entity; currentEntity != null; currentEntity = currentEntity.getSuperObject()) {
            if (SYSTEM_IMAGE.equals(currentEntity.getName())) {
                return true;
            }
        }
        return false;
    
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IsSpecializationOfSystemImage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
