// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import documentgenerationformendix.proxies.Association;
import documentgenerationformendix.proxies.MicroflowInfo;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import com.mendix.systemwideinterfaces.core.UserAction;

public class RetrieveMicroflowsReturningList extends UserAction<java.util.List<IMendixObject>>
{
	public RetrieveMicroflowsReturningList(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger("RetrieveMicroflowsReturningList");
		List<IMendixObject> resultList = new ArrayList<>();
		Set<String> microflowNames = Core.getMicroflowNames();

		for (String microflowName : microflowNames) {
		    try {
		        IDataType returnType = Core.getReturnType(microflowName);
		        
		        if (returnType != null && returnType.isList()) {
		            String entityType = returnType.getObjectType();
		            if (entityType == null) {
		                entityType = "Unknown";
		            }
		            
		            IMendixObject microflowObject = Core.instantiate(getContext(), MicroflowInfo.getType());
		            microflowObject.setValue(getContext(), "CompleteName", microflowName);
		            microflowObject.setValue(getContext(), "Entity", entityType);
		            
		            resultList.add(microflowObject);
		        }
		    } catch (Exception e) {
		        logger.error("Error processing microflow: " + microflowName, e);
		    }
		}

		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveMicroflowsReturningList";
	}

	// BEGIN EXTRA CODE
	
	// END EXTRA CODE
}
