// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import documentgenerationformendix.helpers.StaticFunctions;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Allows for merging documents based on a MergeData Object, Word template System.FileDoc and OutputDoc System.FileDocument, then returns true or false.
 */
public class SimpleMerge extends UserAction<java.lang.Boolean>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(mergeData, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __mergeData;
	private final java.util.List<documentgenerationformendix.proxies.MergeDataColumn> mergeData;
	/** @deprecated use wordTemplate.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __wordTemplate;
	private final system.proxies.FileDocument wordTemplate;
	/** @deprecated use outputDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __outputDoc;
	private final system.proxies.FileDocument outputDoc;
	private final documentgenerationformendix.proxies.OutputType outputType;

	public SimpleMerge(
		IContext context,
		java.util.List<IMendixObject> _mergeData,
		IMendixObject _wordTemplate,
		IMendixObject _outputDoc,
		java.lang.String _outputType
	)
	{
		super(context);
		this.__mergeData = _mergeData;
		this.mergeData = java.util.Optional.ofNullable(_mergeData)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(mergeDataElement -> documentgenerationformendix.proxies.MergeDataColumn.initialize(getContext(), mergeDataElement))
			.collect(java.util.stream.Collectors.toList());
		this.__wordTemplate = _wordTemplate;
		this.wordTemplate = _wordTemplate == null ? null : system.proxies.FileDocument.initialize(getContext(), _wordTemplate);
		this.__outputDoc = _outputDoc;
		this.outputDoc = _outputDoc == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputDoc);
		this.outputType = _outputType == null ? null : documentgenerationformendix.proxies.OutputType.valueOf(_outputType);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (__mergeData == null) {
			throw new IllegalArgumentException("Merge Data is empty");
		} else if (__mergeData.size() < 2) {
			throw new IllegalArgumentException("Merge Data has less than 2 columns");
		}	
		
		StaticFunctions.simpleMerge(this.getContext(), __wordTemplate, mergeData, outputType, __outputDoc);
	    return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SimpleMerge";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
