// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgenerationformendix.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import documentgenerationformendix.helpers.StaticFunctions;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Wil merge the list of objects in the template by Name. Use the name of your attributes in your template.
 */
public class SimpleMergeList extends UserAction<java.lang.Boolean>
{
	private final java.util.List<IMendixObject> mergeTableData;
	/** @deprecated use wordTemplate.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __wordTemplate;
	private final system.proxies.FileDocument wordTemplate;
	/** @deprecated use outputDoc.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __outputDoc;
	private final system.proxies.FileDocument outputDoc;
	private final documentgenerationformendix.proxies.OutputType outputType;

	public SimpleMergeList(
		IContext context,
		java.util.List<IMendixObject> _mergeTableData,
		IMendixObject _wordTemplate,
		IMendixObject _outputDoc,
		java.lang.String _outputType
	)
	{
		super(context);
		this.mergeTableData = _mergeTableData;
		this.__wordTemplate = _wordTemplate;
		this.wordTemplate = _wordTemplate == null ? null : system.proxies.FileDocument.initialize(getContext(), _wordTemplate);
		this.__outputDoc = _outputDoc;
		this.outputDoc = _outputDoc == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputDoc);
		this.outputType = _outputType == null ? null : documentgenerationformendix.proxies.OutputType.valueOf(_outputType);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (mergeTableData == null) {
			throw new IllegalArgumentException("Merge Table Data is empty");
		} 
		
		StaticFunctions.simpleMergeTable(this.getContext(), __wordTemplate, mergeTableData, outputType, __outputDoc);
	    return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SimpleMergeList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
