// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package stringstream.actions;

import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class StringStream_Append extends UserAction<java.lang.Void>
{
	/** @deprecated use StringStream.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __StringStream;
	private final stringstream.proxies.StringStream StringStream;
	private final java.lang.String StringToAppend;

	public StringStream_Append(
		IContext context,
		IMendixObject _stringStream,
		java.lang.String _stringToAppend
	)
	{
		super(context);
		this.__StringStream = _stringStream;
		this.StringStream = _stringStream == null ? null : stringstream.proxies.StringStream.initialize(getContext(), _stringStream);
		this.StringToAppend = _stringToAppend;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		return appendStringToMemoryBuffer();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringStream_Append";
	}

	// BEGIN EXTRA CODE
	private Void appendStringToMemoryBuffer() throws Exception
	{
		try
		{
			// Make a buffer and store in the context if not already there
			OutputStream output = (OutputStream) getContext().getVariables().computeIfAbsent(StringStream.getUID() + "-Output", 
					(k) -> new ByteArrayOutputStream());
			Writer writer = (Writer) getContext().getVariables().computeIfAbsent(StringStream.getUID() + "-BufferWriter",
					(k) -> new BufferedWriter(new OutputStreamWriter(output)));
			
			// write the string to the end of the buffer
			writer.write(StringToAppend);
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}

		return null;
	}	
	// END EXTRA CODE
}
