// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package stringstream.actions;

import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class StringStream_ExportToString extends UserAction<java.lang.String>
{
	/** @deprecated use StringStream.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __StringStream;
	private final stringstream.proxies.StringStream StringStream;

	public StringStream_ExportToString(
		IContext context,
		IMendixObject _stringStream
	)
	{
		super(context);
		this.__StringStream = _stringStream;
		this.StringStream = _stringStream == null ? null : stringstream.proxies.StringStream.initialize(getContext(), _stringStream);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return moveMemoryBufferToDocument();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringStream_ExportToString";
	}

	// BEGIN EXTRA CODE
	private String moveMemoryBufferToDocument()
	{
		try
		{
			// Make a buffer and store in the context if not already there and ensure stream is flushed
			ByteArrayOutputStream output = (ByteArrayOutputStream) getContext().getVariables().computeIfAbsent(StringStream.getUID()+ "-Output",
					(k) -> new ByteArrayOutputStream());
			BufferedWriter writer = (BufferedWriter) getContext().getVariables().computeIfAbsent(StringStream.getUID() + "-BufferWriter",
					(k) -> new BufferedWriter(new OutputStreamWriter(output)));
			writer.flush();

			// Drop the buffer into the FileDocument
			String ResultString=output.toString();

			
			// Delete the buffer
			getContext().getVariables().remove(StringStream.getUID() + "-BufferWriter");
			getContext().getVariables().remove(StringStream.getUID() + "-Output");
			
			return ResultString;
		}
		catch (IOException e)
		{
			throw new RuntimeException(e);
		}

		
	}
	// END EXTRA CODE
}
