// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package scheduling.actions;

import java.util.HashMap;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetObjectByGuid extends CustomJavaAction<IMendixObject>
{
	private java.lang.Long ObjectID;
	private java.lang.String Entity;

	public GetObjectByGuid(IContext context, java.lang.Long ObjectID, java.lang.String Entity)
	{
		super(context);
		this.ObjectID = ObjectID;
		this.Entity = Entity;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext c = this.getContext();
		List<IMendixObject> items = Core.retrieveXPathQuery(c, String.format("//%s[id = '%s']", this.Entity, this.ObjectID), 1, 0, new HashMap<String, String>());
		if (items == null || items.size() == 0) {
			return null;
		}
		return items.get(0);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetObjectByGuid";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
