// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ciphixscheduler.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JAVA_Get_Object_ByGuid extends UserAction<IMendixObject>
{
	private final java.lang.String entityToReturn;
	private final java.lang.String objectGuid;

	public JAVA_Get_Object_ByGuid(
		IContext context,
		java.lang.String _entityToReturn,
		java.lang.String _objectGuid
	)
	{
		super(context);
		this.entityToReturn = _entityToReturn;
		this.objectGuid = _objectGuid;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
        return Core.retrieveId(getContext(), Core.createMendixIdentifier(objectGuid));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAVA_Get_Object_ByGuid";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
