// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ciphixscheduler.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import ciphixscheduler.proxies.ENUM_EventStyle;
import java.util.Optional;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Use this Java action as a template for your own String-to-Enumeration conversions.
 * Studio Pro requires specifying the exact Enumeration to return in the definition of a Java action so we cannot provide a generic implementation.
 * This implementation will throw a NoSuchElementException if an invalid toConvert parameter is given, so remember to handle this error gracefully.
 */
public class JAVA_Parse_EventStyle extends UserAction<java.lang.String>
{
	private final java.lang.String toConvert;

	public JAVA_Parse_EventStyle(
		IContext context,
		java.lang.String _toConvert
	)
	{
		super(context);
		this.toConvert = _toConvert;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        Optional<ENUM_EventStyle> result = this.enumFromString(ENUM_EventStyle.class, toConvert);
        return result.orElseThrow().name();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAVA_Parse_EventStyle";
	}

	// BEGIN EXTRA CODE
	private static final ILogNode lognode = Core.getLogger("Ciphix scheduler");
    private <E extends Enum<E>> Optional<E> enumFromString(final Class<E> enumClass, final String value) {
        try {
            if (value != null) {
                return Optional.of(E.valueOf(enumClass, value));
            }
        } catch (IllegalArgumentException iae) {
			lognode.warn(String.format("No enumeration with value %s found", value));
        }
        return Optional.empty();
    }
	// END EXTRA CODE
}
