// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} schedulerName
 * @param {boolean} zoomIn
 * @returns {Promise.<void>}
 */
export async function JS_Scheduler_Zoom(schedulerName, zoomIn) {
	// BEGIN USER CODE
	window.dispatchEvent(new CustomEvent("ciphix_scheduler_events", { detail: { schedulerName, action: zoomIn ? 'zoomIn' : 'zoomOut'} }));
	// END USER CODE
}
