// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} schedulerName
 * @param {Big} amount - Can be negative
 * @returns {Promise.<void>}
 */
export async function JS_Scheduler_ChangeShift(schedulerName, amount) {
	// BEGIN USER CODE
	window.dispatchEvent(new CustomEvent("ciphix_scheduler_events", { detail: { schedulerName, action: "changeShift", amount } }));
	// END USER CODE
}
