// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package systemmanagement.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.CoreException;
import com.mendix.core.Core;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * For the entity having entityname, this java action will delete the 500 oldest objects determined by the attribute 'createdDate'.
 */
public class Entity_DeleteOldestxObjects extends UserAction<java.lang.Void>
{
	private final java.lang.String EntityName;
	private final java.lang.Long NumberOfObjectsToDelete;

	public Entity_DeleteOldestxObjects(
		IContext context,
		java.lang.String _entityName,
		java.lang.Long _numberOfObjectsToDelete
	)
	{
		super(context);
		this.EntityName = _entityName;
		this.NumberOfObjectsToDelete = _numberOfObjectsToDelete;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE

		try {
			IContext context = getContext();
			// Get the list of objects that we are going to delete
			List<IMendixObject> ObjectsToDelete;
			try {
				// Get the list of objects that we are going to delete
				ObjectsToDelete = getXOldestObjects(EntityName, NumberOfObjectsToDelete.intValue(), context);
			} catch (CoreException e) {
				Core.getLogger("Entity_DeleteOldestxObjects").error("Failed to retrieve the oldest objects of entity " + EntityName + ". " + e.getMessage());
				return null;	
			}
			// Check if the list is empty
			if (ObjectsToDelete.isEmpty()) {
				Core.getLogger("Entity_DeleteOldestxObjects").info("No objects to delete for entity " + EntityName);
				return null;
			}
			// Do the deletion
			Core.delete(context, ObjectsToDelete);
		
		} catch (Exception e) {
			throw new CoreException("The oldest " + NumberOfObjectsToDelete + " objects of entity " + EntityName + " have not been deleted. " + e.getMessage());
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Entity_DeleteOldestxObjects";
	}

	// BEGIN EXTRA CODE
	/**
	 * This function return the x oldest objects of entity y. NB. This only will
	 * work if the entity has the attribute 'createdDate' set to yes, or is one of
	 * the three mentioned entities in module 'System'.
	 *
	 * @param EntityName              Name of the entity, including the Module in
	 *                                the format 'ModuleName.EntityName'
	 * @param NumberOfObjectsToDelete The number of objects that will get deleted
	 * @param context
	 * @return a list x of the oldest objects of the specified entity
	 * @throws CoreException
	 */
public static List<IMendixObject> getXOldestObjects(String EntityName, Integer NumberOfObjectsToDelete,
        IContext context) throws CoreException {
    String query = String.format("//%s", EntityName);
    String Sorting = "createdDate";

    IMetaObject metaObject = Core.getMetaObject(EntityName);
    if (metaObject != null) {
        IMetaPrimitive createdDateAttribute = metaObject.getMetaPrimitive("createdDate");
        if (createdDateAttribute == null) {
            if (EntityName.equals("System.ScheduleEventInformation")) {
                Sorting = "EndTime";
            } else if (EntityName.equals("System.QueuedTask") || EntityName.equals("System.ProcessedQueueTask")) {
                Sorting = "Created";
            } else {
                throw new CoreException("The entity " + EntityName + " does not have a 'createdDate' attribute.");
            }
        }
    } else {
        throw new CoreException("The entity " + EntityName + " does not exist.");
    }

    return Core.createXPathQuery(query)
        .setAmount(NumberOfObjectsToDelete)
        .addSort(Sorting, true) // Sort by createdDate in ascending order (if false, it will be descending)
        .execute(context);
}

	// END EXTRA CODE
}
