// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package systemmanagement.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Java_action_GetScheduledEvents extends UserAction<java.lang.String>
{
	public Java_action_GetScheduledEvents(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String ScheduledEvents = new String();
		java.util.Set<java.lang.String> ScEs = Core.getConfiguration().getMyScheduledEvents();

		for (String ScE : ScEs) {
			ScheduledEvents += "{\"ScEName\":\"" + ScE + "\"},";
			com.mendix.core.conf.Configuration.ScheduledEventExecution ScEExecution = Core.getConfiguration()
					.getScheduledEventExecution();
		}
		return "[" + ScheduledEvents + "]";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action_GetScheduledEvents";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
