// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package systemmanagement.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Given a string containing an email. Using this value to find a person having this email and return that person's useraccount.
 * This only works if module Person is present in the application. But if it is not, it returns empty.
 * You can easily modify this java-code, to search in your app's email-attribute finding the useraccount.
 */
public class UserAccount_GetFromPersonByEmail extends UserAction<IMendixObject>
{
	private final java.lang.String EmailFromPerson;

	public UserAccount_GetFromPersonByEmail(
		IContext context,
		java.lang.String _emailFromPerson
	)
	{
		super(context);
		this.EmailFromPerson = _emailFromPerson;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Todo: retrieve the Person.Person by Person.Person/Email =
		// this.EmailFromPerson and return the System.User that is associated with it.
		// See https://docs.mendix.com/refguide/java-programming
		try {
			// Object<IMendixObject> FoundPerson = Something.getPerson(this.EmailFromPerson);
			// List<IMendixObject> listSystemUsers = Core.retrieveByPath(getContext(), FoundPerson.getMendixObject(),
			// 		"Person.Person_User");
			// if (listSystemUsers.size() > 0) {
			// 	List<IUser> listOneSystemUser = Core.retrieveByPath(getContext(), listSystemUsers.get(0), "Person.Person_User");
			// 	if (listOneSystemUser.size() > 0) {
			// 		return listOneSystemUser.get(0);
			// 	}
			// } else {
			// 	return null;
			// }
			return null;
		} catch (Exception e) {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UserAccount_GetFromPersonByEmail";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
