// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import advanced_excel.proxies.DocumentType;
import advanced_excel.Utils;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.AreaReference;
import org.apache.poi.ss.util.CellReference;
import org.apache.poi.ss.SpreadsheetVersion;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFName;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFName;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Write a converted value to a cell, defined by its name
 * Accepts format for the target cell
 */
public class Cell_WriteByName extends UserAction<java.lang.Boolean>
{
	private final java.lang.String WorkbookID;
	private final java.lang.String CellName;
	private final java.lang.String CellValue;
	private final advanced_excel.proxies.CellType CellType;
	/** @deprecated use CellFormat.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CellFormat;
	private final advanced_excel.proxies.CellFormat CellFormat;

	public Cell_WriteByName(
		IContext context,
		java.lang.String _workbookID,
		java.lang.String _cellName,
		java.lang.String _cellValue,
		java.lang.String _cellType,
		IMendixObject _cellFormat
	)
	{
		super(context);
		this.WorkbookID = _workbookID;
		this.CellName = _cellName;
		this.CellValue = _cellValue;
		this.CellType = _cellType == null ? null : advanced_excel.proxies.CellType.valueOf(_cellType);
		this.__CellFormat = _cellFormat;
		this.CellFormat = _cellFormat == null ? null : advanced_excel.proxies.CellFormat.initialize(getContext(), _cellFormat);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			DocumentType docType = Utils.GetDocumentType(WorkbookID);
			Workbook workbook = Utils.GetWorkBook(WorkbookID);
			if (workbook == null) {
				logger.error("ERROR in Advanced_Excel.Cell_WriteByName:\nWorkbook object not found\nyou have to use Workbook_Create, Workbook_Open or Workbook_LoadFile to create the Workbook object");
				return false;
			}
			
			if (docType == DocumentType.XLS) {
				HSSFCellStyle style = ((HSSFWorkbook)workbook).createCellStyle();
				Utils.CreateStyle(workbook, style, this.CellFormat, docType);
				if (this.CellType == CellType.datetime) {
					style.setDataFormat(workbook.getCreationHelper().createDataFormat().getFormat("yyyy-MM-dd HH:mm:ss"));
				}
				
				Boolean AutofitColumn = false;
				String CustomFormat = null;
				if (this.CellFormat != null)
				{
					AutofitColumn = this.CellFormat.getAutofitColumn();
					CustomFormat = this.CellFormat.getCustomFormat();
				}

				// retrieve the named range
				HSSFName aNamedCell = ((HSSFWorkbook)workbook).getName(CellName);

				// retrieve the cell at the named range and test its contents
				AreaReference aref = new AreaReference(aNamedCell.getRefersToFormula(), SpreadsheetVersion.EXCEL97);
				CellReference[] crefs = aref.getAllReferencedCells();
				for (int i=0; i<crefs.length; i++) {
					HSSFSheet sheet = ((HSSFWorkbook)workbook).getSheet(crefs[i].getSheetName());
					HSSFRow row = sheet.getRow(crefs[i].getRow());
					Short colNum = crefs[i].getCol();
					HSSFCell cell = row.getCell(colNum);

					Utils.SetCellValue(workbook, cell, this.CellType, CellValue);
					if (CustomFormat != null) {
						style.setDataFormat(workbook.getCreationHelper().createDataFormat().getFormat(CustomFormat));
					}
					
					if (CellValue != null && CellValue.indexOf('\n') != -1) {
						HSSFCellStyle newStyle = ((HSSFWorkbook)workbook).createCellStyle();
						newStyle.cloneStyleFrom(style);
						newStyle.setWrapText(true);
						cell.setCellStyle(newStyle);
					} else if (this.CellFormat != null) {
						cell.setCellStyle(style);
					}
					
					if (AutofitColumn) {
						sheet.autoSizeColumn(colNum);
					}
				}
			} else {
				XSSFCellStyle style = ((XSSFWorkbook)workbook).createCellStyle();
				Utils.CreateStyle(workbook, style, this.CellFormat, docType);
				if (this.CellType == CellType.datetime) {
					style.setDataFormat(workbook.getCreationHelper().createDataFormat().getFormat("yyyy-MM-dd HH:mm:ss"));
				}
				
				Boolean AutofitColumn = false;
				String CustomFormat = null;
				if (this.CellFormat != null)
				{
					AutofitColumn = this.CellFormat.getAutofitColumn();
					CustomFormat = this.CellFormat.getCustomFormat();
				}

				// retrieve the named range
				XSSFName aNamedCell = ((XSSFWorkbook)workbook).getName(CellName);

				// retrieve the cell at the named range and test its contents
				AreaReference aref = new AreaReference(aNamedCell.getRefersToFormula(), SpreadsheetVersion.EXCEL2007);
				CellReference[] crefs = aref.getAllReferencedCells();
				for (int i=0; i<crefs.length; i++) {
					XSSFSheet sheet = ((XSSFWorkbook)workbook).getSheet(crefs[i].getSheetName());
					XSSFRow row = sheet.getRow(crefs[i].getRow());
					Short colNum = crefs[i].getCol();
					XSSFCell cell = row.getCell(colNum);

					Utils.SetCellValue(workbook, cell, this.CellType, CellValue);
					if (CustomFormat != null) {
						style.setDataFormat(workbook.getCreationHelper().createDataFormat().getFormat(CustomFormat));
					}
					
					if (CellValue != null && CellValue.indexOf('\n') != -1) {
						XSSFCellStyle newStyle = ((XSSFWorkbook)workbook).createCellStyle();
						newStyle.cloneStyleFrom(style);
						newStyle.setWrapText(true);
						cell.setCellStyle(newStyle);
					} else if (this.CellFormat != null) {
						cell.setCellStyle(style);
					}
				
					if (AutofitColumn) {
						sheet.autoSizeColumn(colNum);
					}
				}
			}
			
			return true;
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.Cell_WriteByName: " + e.getMessage() + "\n" + e.toString(), e);
			return false;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Cell_WriteByName";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
