// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import advanced_excel.proxies.DocumentType;
import advanced_excel.Utils;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellReference;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFName;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFName;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.DefaultIndexedColorMap;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Set a name for a cell
 */
public class Cell_SetName extends UserAction<java.lang.Boolean>
{
	private final java.lang.String WorkbookID;
	private final java.lang.String SheetName;
	private final java.lang.Long Row;
	private final java.lang.Long Column;
	private final java.lang.String CellName;

	public Cell_SetName(
		IContext context,
		java.lang.String _workbookID,
		java.lang.String _sheetName,
		java.lang.Long _row,
		java.lang.Long _column,
		java.lang.String _cellName
	)
	{
		super(context);
		this.WorkbookID = _workbookID;
		this.SheetName = _sheetName;
		this.Row = _row;
		this.Column = _column;
		this.CellName = _cellName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			DocumentType docType = Utils.GetDocumentType(WorkbookID);
			Workbook workbook = Utils.GetWorkBook(WorkbookID);
			if (workbook == null) {
				logger.error("ERROR in Advanced_Excel.Cell_SetName:\nWorkbook object not found\nyou have to use Workbook_Create, Workbook_Open or Workbook_LoadFile to create the Workbook object");
				return false;
			}
			
			if (docType == DocumentType.XLS) {
				HSSFSheet sheet = ((HSSFWorkbook)workbook).getSheet(this.SheetName);
				if (sheet == null) { throw new Exception("Sheet: " + this.SheetName + " not found!"); }
				
				Integer rowNum = this.Row.intValue();
				Integer colNum = this.Column.intValue();
				
				HSSFRow row = sheet.getRow(rowNum);
				if (row == null) {
					row = sheet.createRow(rowNum);
				}
				HSSFCell cell = row.getCell(colNum);
				if (cell == null) {
					cell = row.createCell(colNum);
				}
				String Letter = CellReference.convertNumToColString(colNum);
				String formula = "'" + this.SheetName + "'!$" + Letter + "$" + (rowNum + 1);
				
				HSSFName name = ((HSSFWorkbook)workbook).createName();
				name.setNameName(CellName);
				name.setRefersToFormula(formula);
			} else {
				XSSFSheet sheet = ((XSSFWorkbook)workbook).getSheet(this.SheetName);
				if (sheet == null) { throw new Exception("Sheet: " + this.SheetName + " not found!"); }
				
				Integer rowNum = this.Row.intValue();
				Integer colNum = this.Column.intValue();
				
				XSSFRow row = sheet.getRow(rowNum);
				if (row == null) {
					row = sheet.createRow(rowNum);
				}
				XSSFCell cell = row.getCell(colNum);
				if (cell == null) {
					cell = row.createCell(colNum);
				}
				String Letter = CellReference.convertNumToColString(colNum);
				String formula = "'" + this.SheetName + "'!$" + Letter + "$" + (rowNum + 1);
				
				XSSFName name = ((XSSFWorkbook)workbook).createName();
				name.setNameName(CellName);
				name.setRefersToFormula(formula);
			}
			
			return true;
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.Cell_SetName: " + e.getMessage() + "\n" + e.toString(), e);
			return false;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Cell_SetName";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
