// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import advanced_excel.proxies.Data;
import advanced_excel.proxies.CellType;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.objectmanagement.member.*;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.math.BigDecimal;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Update an object with row of excel file
 */
public class UpdateObject extends UserAction<java.lang.Boolean>
{
	private final java.lang.String WorkbookID;
	private final java.lang.String SheetName;
	private final IMendixObject ObjectInput;
	private final java.lang.Long Row;
	private final java.lang.String Columns;
	private final java.lang.String Attributes;

	public UpdateObject(
		IContext context,
		java.lang.String _workbookID,
		java.lang.String _sheetName,
		IMendixObject _objectInput,
		java.lang.Long _row,
		java.lang.String _columns,
		java.lang.String _attributes
	)
	{
		super(context);
		this.WorkbookID = _workbookID;
		this.SheetName = _sheetName;
		this.ObjectInput = _objectInput;
		this.Row = _row;
		this.Columns = _columns;
		this.Attributes = _attributes;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			IContext context = this.getContext();
			
			String[] attributes = Attributes == null ? new String[0] : Attributes.split(";");
			String[] columns = Columns == null ? new String[0] : Columns.split(";");
			
			for (int i = 0; i < attributes.length; i++) {
				Cell_ReadByIndex read = new Cell_ReadByIndex(context, WorkbookID, SheetName, Row, Long.parseLong(columns[i]));
				String valStr = read.executeAction();
				if (valStr == null) { continue; }
				if (valStr.equals(null) || valStr.equals("")) { continue; }
				
				IMendixObjectMember<?> m = ObjectInput.getMember(context, attributes[i]);
				if (m.isVirtual()) {
					continue;
				}
				if (m instanceof MendixAutoNumber) {
					continue;
				}
				
				if (m instanceof MendixInteger) { ObjectInput.setValue​(context, attributes[i], Integer.parseInt(valStr)); }
				else if (m instanceof MendixBoolean) { ObjectInput.setValue​(context, attributes[i], Boolean.parseBoolean(valStr)); }
				else if (m instanceof MendixDecimal) { ObjectInput.setValue​(context, attributes[i], new BigDecimal(valStr)); }
				else if (m instanceof MendixLong) { ObjectInput.setValue​(context, attributes[i], Long.parseLong(valStr)); }
				else if (m instanceof MendixString) { ObjectInput.setValue​(context, attributes[i], valStr);}
				else if (m instanceof MendixDateTime) {
					DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); 
					ObjectInput.setValue​(context, attributes[i], dateFormat.parse(valStr));
				}
			}
			
			return true;
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.UpdateObject: " + e.getMessage() + "\n" + e.toString(), e);
			return false;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UpdateObject";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
