// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import java.io.InputStream;
import advanced_excel.proxies.DocumentType;
import advanced_excel.Utils;
import org.apache.poi.openxml4j.util.ZipSecureFile;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Opens an existing workbook for editing
 */
public class Workbook_LoadFile extends UserAction<java.lang.String>
{
	/** @deprecated use ExcelFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ExcelFile;
	private final advanced_excel.proxies.AdvancedExcel ExcelFile;

	public Workbook_LoadFile(
		IContext context,
		IMendixObject _excelFile
	)
	{
		super(context);
		this.__ExcelFile = _excelFile;
		this.ExcelFile = _excelFile == null ? null : advanced_excel.proxies.AdvancedExcel.initialize(getContext(), _excelFile);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			ZipSecureFile.setMinInflateRatio(0);
			DocumentType docType = this.ExcelFile.getDocumentType();
			InputStream inStream = Core.getFileDocumentContent(getContext(), ExcelFile.getMendixObject());
			
			Workbook workbook;
			if (docType == DocumentType.XLS) {
				workbook = new HSSFWorkbook(inStream);
			} else {
				workbook = new XSSFWorkbook(inStream);
			}
			/*
			Utils.SetDocumentType(docType);
			Utils.SetWorkBook(workbook);
			*/
			return Utils.AddWorkBook(workbook, docType);
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.Workbook_LoadFile: " + e.getMessage() + "\n" + e.toString(), e);
			return null;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Workbook_LoadFile";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
