// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} environmentLetter - D, T, A or P. Or some more obscure letter.
 * @returns {Promise.<void>}
 */
export async function JS_AddEnvironmentclassToBody(environmentLetter) {
	// BEGIN USER CODE
const body = document.body;

if (environmentLetter == 'P') {
   body.classList.add('prod-env');
}   
else if (environmentLetter == 'D') { /*Running locally on the developer's a laptop.*/
   body.classList.add('local-env');
}
else if (environmentLetter == 'S') { /*For sandbox-environment*/
   body.classList.add('dev-env');
}
else if (environmentLetter == 'T') {
   body.classList.add('test-env');
}
else if (environmentLetter == 'A') {
   body.classList.add('accp-env');
}
else {
   body.classList.add('other-env');
}
	// END USER CODE
}
