// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} environmentLetter - D, T, A or P. Or some more obscure letter.
 * @returns {Promise.<void>}
 */
export async function JS_AddEnvironmentclassToBody_BasedOnURL(environmentLetter) {
	// BEGIN USER CODE
const body = document.body;

if ((window.location.href.indexOf("prod.") > -1) ||
    (window.location.href.indexOf("prd.") > -1)) {
   body.classList.add('prod-env');
}   
else if ((window.location.href.indexOf(":808") > -1) ||
    (window.location.href.indexOf("localhost:") > -1))  {
   body.classList.add('local-env');
}
else if (window.location.href.indexOf("-sandbox.") > -1) {
   body.classList.add('dev-env');
}
else if ((window.location.href.indexOf("-test.") > -1) ||
         (window.location.href.indexOf("-tst.") > -1)) {
   body.classList.add('test-env');
}
else if ((window.location.href.indexOf("-accp.") > -1) ||
         (window.location.href.indexOf("-acc.") > -1)) {
   body.classList.add('accp-env');
}
else if (window.location.href.indexOf("soak.") > -1) {
   body.classList.add('soak-env');
}
else if (window.location.href.indexOf("performance.") > -1) {
   body.classList.add('perf-env');
}
else if (window.location.href.indexOf("repo.") > -1) {
   body.classList.add('repo-env');
}
else if (window.location.href.indexOf("trai.") > -1) {
   body.classList.add('trai-env');
}
else {
   body.classList.add('other-env');
}
	// END USER CODE
}
