// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} loginToken
 * @returns {Promise.<void>}
 */
export async function JS_LoginUserAccountRedirect(loginToken) {
	// BEGIN USER CODE
	var xhr = new XMLHttpRequest();
	var url = mx.appUrl + "autologin/";
	var params = "loginToken=" + loginToken;
	xhr.open("POST",url,false);
	xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");
	xhr.send(params);
	location.reload();
	// END USER CODE
}
