// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Open page <yourapp>/login.html, and do this in the current window.
 * @returns {Promise.<void>}
 */
export async function LoginPage_ShowInSameWindow() {
	// BEGIN USER CODE
	window.location.replace("login.html");
	// END USER CODE
}
