// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package approntolicenser.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import approntolicenser.helpers.ApprontoLicenser;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This java action is activating the license
 */
public class ActivateProductLicenseJava extends UserAction<java.lang.Boolean>
{
	private final java.lang.String license;
	private final java.lang.Long maxUsers;
	private final java.lang.String productName;

	public ActivateProductLicenseJava(
		IContext context,
		java.lang.String _license,
		java.lang.Long _maxUsers,
		java.lang.String _productName
	)
	{
		super(context);
		this.license = _license;
		this.maxUsers = _maxUsers;
		this.productName = _productName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ApprontoLicenser WSlicense = null;
		WSlicense = ApprontoLicenser.getLicense(this.productName);
		ApprontoLicenser.validate(this.getContext(), WSlicense, license, maxUsers.intValue());
		return WSlicense.getValidLicense();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ActivateProductLicenseJava";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
