// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Applies AES encryption to the value string using a symmetric key. 
 * The keylength should exactly be 16 characters (128 bit).
 */
public class DecryptString_AESwithoutSalt extends UserAction<java.lang.String>
{
	private final java.lang.String valueToDecrypt;
	private final java.lang.String key;

	public DecryptString_AESwithoutSalt(
		IContext context,
		java.lang.String _valueToDecrypt,
		java.lang.String _key
	)
	{
		super(context);
		this.valueToDecrypt = _valueToDecrypt;
		this.key = _key;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return decryptString(key, valueToDecrypt);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecryptString_AESwithoutSalt";
	}

	// BEGIN EXTRA CODE
	public static String decryptString(String key, String valueToDecrypt) throws Exception {
		if (valueToDecrypt == null) {
			return null;
		}
		if (key == null) {
			throw new MendixRuntimeException("Key should not be empty");
		}
		Cipher c = Cipher.getInstance("AES");
		SecretKeySpec k = new SecretKeySpec(key.getBytes(), "AES");
		byte[] encryptedData = Base64.getDecoder().decode(valueToDecrypt.getBytes());
		c.init(Cipher.DECRYPT_MODE, k);
		return new String(c.doFinal(encryptedData));
	}
	// END EXTRA CODE
}
