// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Decrypts an AES encrypted string.
 * The keylength should exactly be 16 characters (128 bit).
 */
public class EncryptString_AESwithoutSalt extends UserAction<java.lang.String>
{
	private final java.lang.String valueToEncrypt;
	private final java.lang.String key;

	public EncryptString_AESwithoutSalt(
		IContext context,
		java.lang.String _valueToEncrypt,
		java.lang.String _key
	)
	{
		super(context);
		this.valueToEncrypt = _valueToEncrypt;
		this.key = _key;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return encryptString(key, valueToEncrypt);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EncryptString_AESwithoutSalt";
	}

	// BEGIN EXTRA CODE
	public static String encryptString(String key, String valueToEncrypt) throws Exception {
		if (valueToEncrypt == null) {
			return null;
		}
		if (key == null) {
			throw new MendixRuntimeException("Key should not be empty");
		}
		Cipher c = Cipher.getInstance("AES");
		SecretKeySpec k = new SecretKeySpec(key.getBytes(), "AES");
		c.init(Cipher.ENCRYPT_MODE, k);
		byte[] encryptedData = c.doFinal(valueToEncrypt.getBytes());

		return Base64.getEncoder().encodeToString(encryptedData);
	}
	// END EXTRA CODE
}
