// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * param2 and paramName2 are optional (fill empty then)
 * MicroflowToExecute must be the CompleteName (modulename.microflowname)
 */
public class ExecuteUnverifiedMicroflowInOwnTransaction extends UserAction<java.lang.Boolean>
{
	private final IMendixObject Param;
	private final java.lang.String ParamName;
	private final IMendixObject Param2;
	private final java.lang.String ParamName2;
	private final java.lang.String MicroflowToExecute;

	public ExecuteUnverifiedMicroflowInOwnTransaction(
		IContext context,
		IMendixObject _param,
		java.lang.String _paramName,
		IMendixObject _param2,
		java.lang.String _paramName2,
		java.lang.String _microflowToExecute
	)
	{
		super(context);
		this.Param = _param;
		this.ParamName = _paramName;
		this.Param2 = _param2;
		this.ParamName2 = _paramName2;
		this.MicroflowToExecute = _microflowToExecute;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext newContext= this.getContext().getSession().createContext();
		newContext.startTransaction();

		if ( this.Param2 != null && this.ParamName2 != null) 
		{
			Core.microflowCall(this.MicroflowToExecute)
			.withParam(this.ParamName, this.Param)
			.withParam(this.ParamName2, this.Param2)
			.execute(newContext);
		}
		else {
			Core.microflowCall(this.MicroflowToExecute)
			.withParam(this.ParamName, this.Param)
			.execute(newContext);
		}
		newContext.endTransaction();
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteUnverifiedMicroflowInOwnTransaction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
