// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.io.File;
import java.io.FileInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class FileFromResourceToFileDocument extends UserAction<java.lang.Boolean>
{
	private final java.lang.String Filename;
	/** @deprecated use TargetFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __TargetFile;
	private final system.proxies.FileDocument TargetFile;

	public FileFromResourceToFileDocument(
		IContext context,
		java.lang.String _filename,
		IMendixObject _targetFile
	)
	{
		super(context);
		this.Filename = _filename;
		this.__TargetFile = _targetFile;
		this.TargetFile = _targetFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _targetFile);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		String filenamePath = Core.getConfiguration().getResourcesPath().getAbsolutePath() + File.separator + Filename;
		TargetFile.setName(Filename);
		FileInputStream fis = new FileInputStream(filenamePath);
		{
			Core.storeFileDocumentContent(getContext(), TargetFile.getMendixObject(), fis);
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FileFromResourceToFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
