// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.util.Stack;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.ICoreAction;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This action will output the current Stack as a string for debugging purposes
 */
public class GetCurrentMicroflowStack extends UserAction<java.lang.String>
{
	public GetCurrentMicroflowStack(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Retrieve the action stack from the current context
		Stack<ICoreAction<?>> actionStack = this.getContext().getActionStack();

		// We will pop the first entry as this will always be Unnamed-Action-x
		actionStack.pop();

		// Create a StringBuilder to build the string representation of action names
		StringBuilder sb = new StringBuilder();

		// Iterate over the action stack until it is empty
		while (!actionStack.isEmpty()) {
			// Pop the top action from the stack
			ICoreAction<?> action = actionStack.pop();

			// Get the action name
			String actionName = action.getActionName();

			// Append the action name to the StringBuilder.
			sb.append(actionName).append("\n");
		}

		// Return the final string representation of action names
		return sb.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetCurrentMicroflowStack";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
