// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.meta.IMetaEnumValue;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive.PrimitiveType;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Uses the generic function of Mendix to get translated strings
 */
public class GetEnumCaptionForLanguage extends UserAction<java.lang.String>
{
	private final java.lang.String LanguageCode;
	private final java.lang.String EnumKey;

	public GetEnumCaptionForLanguage(
		IContext context,
		java.lang.String _languageCode,
		java.lang.String _enumKey
	)
	{
		super(context);
		this.LanguageCode = _languageCode;
		this.EnumKey = _enumKey;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Get all meta objects in the Mendix model
        Iterable<IMetaObject> metaObjects = Core.getMetaObjects();
        for (IMetaObject metaObject : metaObjects) {
            // Get all attributes of the current meta object
        	for(IMetaPrimitive metaPrimitive : metaObject.getMetaPrimitives())
    		{
        		if(metaPrimitive.getType() == PrimitiveType.Enum)
    			{
        			for(IMetaEnumValue metaEnumValue : metaPrimitive.getEnumValues())
        			{
        				 if(metaEnumValue.getIdentifier().equals(EnumKey))
        					 return Core.getInternationalizedString(LanguageCode, metaEnumValue.getI18NCaptionKey());	 
        			}
    			}
    		}
        }
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetEnumCaptionForLanguage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
