// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.io.IOException;
import java.io.InputStream;
import org.apache.tika.Tika;
import org.apache.tika.io.TikaInputStream;
import org.apache.tika.metadata.Metadata;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Returns the file type (MIME type) of the input file.
 */
public class GetFileType extends UserAction<java.lang.String>
{
	/** @deprecated use inputFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __inputFile;
	private final system.proxies.FileDocument inputFile;

	public GetFileType(
		IContext context,
		IMendixObject _inputFile
	)
	{
		super(context);
		this.__inputFile = _inputFile;
		this.inputFile = _inputFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _inputFile);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
 
		if (inputFile.getMendixObject() != null && inputFile.getHasContents(this.getContext())) {
			FileTypeChecker fileTypeChecker = new FileTypeChecker();
			return fileTypeChecker.getFileType(inputFile.getMendixObject(), this.getContext());
		}

		else {
			throw new NullPointerException("Empty input file in FileIdentifier.");
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileType";
	}

	// BEGIN EXTRA CODE
	public class FileTypeChecker {

		public String getFileType(IMendixObject inputFile, IContext context) throws Exception {

			InputStream inputStream = null;
			TikaInputStream tikaStream = null;
			String mimeType;

			try {
				Tika tika = new Tika();
				inputStream = Core.getFileDocumentContent(context, inputFile);
				tikaStream = TikaInputStream.get(inputStream);
				Metadata metadata = new Metadata();
				mimeType = tika.detect(tikaStream, metadata);

			} finally {
				if (inputStream != null) {
					drainAndClose(inputStream);
					//inputStream.close();
				}

				if (tikaStream != null) {
					tikaStream.close();
				}
			}

			return mimeType.toString();
		}
	}

	public void drainAndClose(InputStream is) {
		boolean done = false;
		while (!done) {
			try {
				is.skip(is.available()); // Skip as many bytes as available
				int nextByte = is.read(); // Try to read one byte further
				if (nextByte < 0) { // End of file reached
					done = true;
				}
			} catch (IOException e) {
				done = true;
			}
		}
		try {
			is.close();
		} catch (IOException e) {
		}
	}
	// END EXTRA CODE
}
