// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.core.Core;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Gets the current IP address of the user when the app is running in the cloud.
 */
public class GetIPaddress extends UserAction<java.lang.String>
{
	public GetIPaddress(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext ctx = getContext();
		if (ctx.getRuntimeRequest().isPresent()) 
		{
			IMxRuntimeRequest request = ctx.getRuntimeRequest().get();
				
			String remoteAddress = request.getRemoteAddr();
			String forwardedFor = request.getHeader("X-Forwarded-For");
			String realIP = request.getHeader("X-Real-IP"); // This is the header which should be used to check the IP address range.
			Core.getLogger("GetIP").debug("New login request (X-Real-IP: " + realIP + ", X-Forwarded-For:" + forwardedFor + ", remote address: " + remoteAddress);
				
			if( realIP == null )
				realIP = forwardedFor;
			if( realIP == null )
				realIP = remoteAddress;
			return realIP;
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetIPaddress";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
