// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import emixacommons.proxies.microflows.Microflows;
import emixacommons.proxies.QueueActionStatus;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Will call microflow SUB_QueueActionStatus_Microflow with the correct microflow name as parameter. If you rename or move your microflow it will still work.
 */
public class GetQueueActionStatusForMicroflow extends UserAction<IMendixObject>
{
	private final java.lang.String MicroflowInTaskQueue;

	public GetQueueActionStatusForMicroflow(
		IContext context,
		java.lang.String _microflowInTaskQueue
	)
	{
		super(context);
		this.MicroflowInTaskQueue = _microflowInTaskQueue;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		QueueActionStatus status = Microflows.sUB_QueueActionStatus_Microflow(getContext(), MicroflowInTaskQueue) ;
		if( status != null ){
			return status.getMendixObject();
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetQueueActionStatusForMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
