// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import java.util.Random;
import java.math.BigInteger;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Generate NL IBAN Bank accounts
 */
public class IBANGenerate extends UserAction<java.lang.String>
{
	public IBANGenerate(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String countryCode = "NL";
        String[] bankCodes = {"ABNA", "INGB", "RABO", "SNSB", "TRIO", "FVLB", "KNAB", "ASNB"};

        Random random = new Random();

         // 1. Generate a random 4-letter bank code
        String randomBankCode = bankCodes[random.nextInt(bankCodes.length)];
		
		// 2. Generate 10 random digits for the account number
        StringBuilder accountNumber = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            accountNumber.append(random.nextInt(10));
        }

        // 3. Create the BBAN (Basic Bank Account Number)
        String bban = randomBankCode + accountNumber.toString();

        // 4. Create the preliminary IBAN with placeholder checksum "00"
        String preliminaryIban = countryCode + "00" + bban;

        // 5. Calculate the Modulo 97 compliant checksum
        String checksum = calculateChecksum(preliminaryIban);

        // 6. Return the full IBAN
        return countryCode + checksum + bban;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IBANGenerate";
	}

	// BEGIN EXTRA CODE
		private static String calculateChecksum(String iban) {
        // Move the first four characters to the end
        String rearrangedIban = iban.substring(4) + iban.substring(0, 4);

        // Convert letters to numbers (A=10, B=11, ...)
        StringBuilder numericString = new StringBuilder();
        for (char c : rearrangedIban.toCharArray()) {
            if (Character.isLetter(c)) {
                int value = Character.toUpperCase(c) - 'A' + 10;
                numericString.append(value);
            } else {
                numericString.append(c);
            }
        }

        // Calculate Modulo 97
        // Use BigInteger to handle the large number
        BigInteger number = new BigInteger(numericString.toString());
        BigInteger modulus = new BigInteger("97");
        int remainder = number.mod(modulus).intValue();

        // Calculate the check digits (98 - remainder)
        int checksumValue = 98 - remainder;
        String checksum = String.valueOf(checksumValue);

        // Add a leading zero if the checksum is a single digit
        if (checksum.length() == 1) {
            return "0" + checksum;
        }

        return checksum;
    }
	// END EXTRA CODE
}
