// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import emixacommons.helper.CacheHolder;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Retrieve the entity from the cache
 */
public class JA_RetrieveEntityFromCache extends UserAction<IMendixObject>
{
	private final java.lang.String EntityToRetrieve;

	public JA_RetrieveEntityFromCache(
		IContext context,
		java.lang.String _entityToRetrieve
	)
	{
		super(context);
		this.EntityToRetrieve = _entityToRetrieve;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (EntityToRetrieve == null) throw new IllegalArgumentException("EntityToRetrieve is empty");
		return CacheHolder.getObject(EntityToRetrieve);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_RetrieveEntityFromCache";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
