// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.io.ByteArrayInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Empties the passed System.FileDocument.
 */
public class MakeFileEmpty extends UserAction<java.lang.Void>
{
	/** @deprecated use FileToEmpty.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __FileToEmpty;
	private final system.proxies.FileDocument FileToEmpty;

	public MakeFileEmpty(
		IContext context,
		IMendixObject _fileToEmpty
	)
	{
		super(context);
		this.__FileToEmpty = _fileToEmpty;
		this.FileToEmpty = _fileToEmpty == null ? null : system.proxies.FileDocument.initialize(getContext(), _fileToEmpty);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		 Core.storeFileDocumentContent(getContext(), FileToEmpty.getMendixObject(), FileToEmpty.getName(),  new ByteArrayInputStream("".getBytes("UTF-8")));
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MakeFileEmpty";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
