// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import org.apache.commons.codec.DecoderException;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import emixacommons.helper.HexHelpers;
import emixacommons.helper.HexHelpers.*;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Converts a Hexadecimal string value to FileDocument content.
 * Provide a file extension, or leave empty for auto detection.
 */
public class ParseHexToFile extends UserAction<java.lang.Void>
{
	private final java.lang.String inputHex;
	/** @deprecated use outputFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __outputFile;
	private final system.proxies.FileDocument outputFile;
	private final java.lang.String fileExtension;

	public ParseHexToFile(
		IContext context,
		java.lang.String _inputHex,
		IMendixObject _outputFile,
		java.lang.String _fileExtension
	)
	{
		super(context);
		this.inputHex = _inputHex;
		this.__outputFile = _outputFile;
		this.outputFile = _outputFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _outputFile);
		this.fileExtension = _fileExtension;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		byte[] data = null;
		if (inputHex == null || inputHex.isEmpty()) {
            throw new IllegalArgumentException("Hex string is null or empty");
        }
		try {
			data = HexHelpers.decodeLenientHex(inputHex);  
		} catch (DecoderException e) {
			e.printStackTrace();
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(e);	
		}
		        
        InputStream inputStream = new ByteArrayInputStream(data);
		
        String ext = fileExtension;
        if(fileExtension == null) {
        	FileSignature signature = HexHelpers.detect(data);
        	ext = signature.extension;
        }
        
		String filename = outputFile.getName().concat(".").concat(ext);
        try {
			Core.storeFileDocumentContent(getContext(), outputFile.getMendixObject(), filename, inputStream);
		} catch (Exception e) {
			e.printStackTrace();
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(e);
		}
        
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ParseHexToFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
