// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import emixacommons.helper.HexHelpers;
import java.nio.charset.StandardCharsets;
import org.apache.commons.codec.DecoderException;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Converts a Hexadecimal string value to text.
 */
public class ParseHexToString extends UserAction<java.lang.String>
{
	private final java.lang.String inputHex;

	public ParseHexToString(
		IContext context,
		java.lang.String _inputHex
	)
	{
		super(context);
		this.inputHex = _inputHex;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String outputString = "";
		if (inputHex == null || inputHex.isEmpty()) {
            throw new IllegalArgumentException("Hex string is null or empty");
        }
		try {
			byte[] bytes = HexHelpers.decodeLenientHex(inputHex);
			outputString = new String(bytes, StandardCharsets.UTF_8);
		} catch (DecoderException e) {
			e.printStackTrace();
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException(e);	
		}
		
		return outputString;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ParseHexToString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
