// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.ImageWriteParam;
import javax.imageio.ImageWriter;
import javax.imageio.stream.ImageInputStream;
import javax.imageio.stream.ImageOutputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Resize image to target width and height.
 * 
 * Aspect ratio can be maintained if a width or height value is given. 
 * When both values are given, and the keepAspectRatio is set to true, the value for width will be used and height will be calculated.
 * 
 */
public class ResizeImage extends UserAction<java.lang.Void>
{
	/** @deprecated use imageObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __imageObject;
	private final system.proxies.Image imageObject;
	private final java.lang.Long targetWidth;
	private final java.lang.Long targetHeight;
	private final java.lang.Boolean keepAspectRatio;
	private final java.math.BigDecimal imageQuality;

	public ResizeImage(
		IContext context,
		IMendixObject _imageObject,
		java.lang.Long _targetWidth,
		java.lang.Long _targetHeight,
		java.lang.Boolean _keepAspectRatio,
		java.math.BigDecimal _imageQuality
	)
	{
		super(context);
		this.__imageObject = _imageObject;
		this.imageObject = _imageObject == null ? null : system.proxies.Image.initialize(getContext(), _imageObject);
		this.targetWidth = _targetWidth;
		this.targetHeight = _targetHeight;
		this.keepAspectRatio = _keepAspectRatio;
		this.imageQuality = _imageQuality;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		float targetQuality = (imageQuality != null) ? imageQuality.floatValue() : 1.0f;
        if (targetQuality > 1.0f || targetQuality < 0.0f) {
            throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Quality must be between 0 and 1");
        }

        try (InputStream inputStream = Core.getImage(getContext(), imageObject.getMendixObject(), false);
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            BufferedImage inputImage = ImageIO.read(inputStream);
            if (inputImage == null) {
                throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Could not read image");
            }

            int[] newDimensions = calculateNewDimensions(inputImage, targetWidth, targetHeight, keepAspectRatio);
            int newWidth = newDimensions[0];
            int newHeight = newDimensions[1];

            String formatName;
            try (InputStream formatStream = Core.getImage(getContext(), imageObject.getMendixObject(), false)) {
                formatName = detectImageFormat(formatStream);
            }

            BufferedImage outputImage = resizeImage(inputImage, newWidth, newHeight);
            writeImage(outputImage, outputStream, formatName, targetQuality);

            try (InputStream newStream = new ByteArrayInputStream(outputStream.toByteArray())) {
                Core.storeFileDocumentContent(getContext(), imageObject.getMendixObject(), newStream);
            }
        }
        return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ResizeImage";
	}

	// BEGIN EXTRA CODE
	/**
	 * 
	 * @param inputImage
	 * @param targetWidth
	 * @param targetHeight
	 * @param keepAspectRatio
	 * @return
	 * 
	 * Calculates target image dimensions based on width, height and/or aspect ratio
	 */
	private int[] calculateNewDimensions(BufferedImage inputImage, Long targetWidth, Long targetHeight, Boolean keepAspectRatio) {
        int originalWidth = inputImage.getWidth();
        int originalHeight = inputImage.getHeight();
        double aspectRatio = (double) originalWidth / originalHeight;

        int newWidth, newHeight;
        if (Boolean.TRUE.equals(keepAspectRatio)) {
            if (targetWidth != null) {
                newWidth = targetWidth.intValue();
                newHeight = (int) Math.round(newWidth / aspectRatio);
            } else if (targetHeight != null) {
                newHeight = targetHeight.intValue();
                newWidth = (int) Math.round(newHeight * aspectRatio);
            } else {
                throw new com.mendix.systemwideinterfaces.MendixRuntimeException("At least one of width or height must be provided when keeping aspect ratio");
            }
        } else {
            newWidth = (targetWidth != null) ? targetWidth.intValue() : originalWidth;
            newHeight = (targetHeight != null) ? targetHeight.intValue() : originalHeight;
        }
        return new int[]{newWidth, newHeight};
    }
	
	
	/**
	 * 
	 * @param inputStream
	 * @return
	 * @throws Exception
	 * 
	 * Detects the image format from an InputStream.
	 */
    private String detectImageFormat(InputStream inputStream) throws Exception {
    	ImageReader reader = null;
        try (ImageInputStream imageInputStream = ImageIO.createImageInputStream(inputStream)) {
            Iterator<ImageReader> readers = ImageIO.getImageReaders(imageInputStream);
            if (!readers.hasNext()) {
                throw new com.mendix.systemwideinterfaces.MendixRuntimeException("No image format detected");
            }
            reader = readers.next();
            return reader.getFormatName().toLowerCase();
        } finally {
            if (reader != null) {
                reader.dispose(); // Explicit resource cleanup
            }
        }
    }
    
    /**
     * 
     * @param inputImage
     * @param newWidth
     * @param newHeight
     * @return
     * 
     * Resize an image to given new height and width 
     */
    private BufferedImage resizeImage(BufferedImage inputImage, int newWidth, int newHeight) {
        Graphics2D g2d = null;
        try {
            int imageType = inputImage.getType();
            if (imageType == BufferedImage.TYPE_CUSTOM || imageType == 0) {
                imageType = inputImage.getColorModel().hasAlpha() ? BufferedImage.TYPE_INT_ARGB : BufferedImage.TYPE_INT_RGB;
            }

            BufferedImage outputImage = new BufferedImage(newWidth, newHeight, imageType);
            g2d = outputImage.createGraphics();
            g2d.drawImage(inputImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH), 0, 0, newWidth, newHeight, null);
            return outputImage;
        } finally {
            if (g2d != null) {
                g2d.dispose(); // Ensure Graphics2D is always disposed
            }
        }
    }
    
    /**
     * 
     * @param outputImage
     * @param outputStream
     * @param formatName
     * @param quality
     * @throws Exception
     * 
     * Writes new image to output
     */
    private void writeImage(BufferedImage outputImage, ByteArrayOutputStream outputStream, String formatName, float quality) throws Exception {
        ImageWriter writer = ImageIO.getImageWritersByFormatName(formatName).next();
        try (ImageOutputStream ios = ImageIO.createImageOutputStream(outputStream)) {
            writer.setOutput(ios);
            ImageWriteParam param = writer.getDefaultWriteParam();

            if (param.canWriteCompressed()) {
                param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
                param.setCompressionQuality(quality);
            }

            writer.write(null, new javax.imageio.IIOImage(outputImage, null, null), param);
        } finally {
            writer.dispose();
        }
    }

	// END EXTRA CODE
}
