// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive.PrimitiveType;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Sets the value for the given attribute. Useful when you have to fill entities with attribute names like Name1, Name2 etc.
 */
public class SetValueForAttribute extends UserAction<java.lang.Boolean>
{
	private final IMendixObject objectParam;
	private final java.lang.String attributeName;
	private final java.lang.String stringForAttribute;
	private final java.lang.Long integerForAttribute;
	private final java.math.BigDecimal decimalForAttribute;
	private final java.util.Date dateTimeForAttribute;

	public SetValueForAttribute(
		IContext context,
		IMendixObject _objectParam,
		java.lang.String _attributeName,
		java.lang.String _stringForAttribute,
		java.lang.Long _integerForAttribute,
		java.math.BigDecimal _decimalForAttribute,
		java.util.Date _dateTimeForAttribute
	)
	{
		super(context);
		this.objectParam = _objectParam;
		this.attributeName = _attributeName;
		this.stringForAttribute = _stringForAttribute;
		this.integerForAttribute = _integerForAttribute;
		this.decimalForAttribute = _decimalForAttribute;
		this.dateTimeForAttribute = _dateTimeForAttribute;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.objectParam != null && this.attributeName != null) {
			if (!this.objectParam.hasMember(attributeName)) {
				Core.getLogger("ApprontoCommon").error("Object does not contain attribute "+ attributeName );
				return false;
			}
 
			try {
				if (this.stringForAttribute != null) {
					if(this.objectParam.getMetaObject().getMetaPrimitive(attributeName).getType() != PrimitiveType.String ) {
						Core.getLogger("ApprontoCommon").error("Attribute "+ attributeName +" is not of the datatype String");
						return false;
					}
					else this.objectParam.setValue(this.getContext(), this.attributeName,this.stringForAttribute);
				} 
				else if (this.integerForAttribute != null) {
					if(this.objectParam.getMetaObject().getMetaPrimitive(attributeName).getType() != PrimitiveType.Integer && this.objectParam.getMetaObject().getMetaPrimitive(attributeName).getType() != PrimitiveType.Long) {
						Core.getLogger("ApprontoCommon").error("Attribute "+ attributeName +" is not of the datatype Integer");
						return false;
					}
					else this.objectParam.setValue(this.getContext(), this.attributeName,this.integerForAttribute);
				}
				else if (this.decimalForAttribute != null) {
					if(this.objectParam.getMetaObject().getMetaPrimitive(attributeName).getType() != PrimitiveType.Decimal ) {
						Core.getLogger("ApprontoCommon").error("Attribute "+ attributeName +" is not of the datatype Decimal");
						return false;
					}
					else this.objectParam.setValue(this.getContext(), this.attributeName,this.decimalForAttribute);
				}
				else if (this.dateTimeForAttribute != null) {
					if(this.objectParam.getMetaObject().getMetaPrimitive(attributeName).getType() != PrimitiveType.DateTime ) {
						Core.getLogger("ApprontoCommon").error("Attribute "+ attributeName +" is not of the datatype DateTime");
						return false;
					}
					else this.objectParam.setValue(this.getContext(), this.attributeName,this.dateTimeForAttribute);
				}
				else {
					return false;
					}
				}
			catch (Exception e) {
				Core.getLogger("ApprontoCommon").error(e.getMessage());
				return false;
			}
			return  true;
		}
		Core.getLogger("ApprontoCommon").error("No object or AttributeName provided");
		return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetValueForAttribute";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
