// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.math.BigInteger;
import java.security.MessageDigest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Performs a SHA1Encrypt() function on an input string parameter, then returns a string.
 */
public class SHA1Encrypt extends UserAction<java.lang.String>
{
	private final java.lang.String Input;

	public SHA1Encrypt(
		IContext context,
		java.lang.String _input
	)
	{
		super(context);
		this.Input = _input;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		MessageDigest digest = MessageDigest.getInstance("SHA-1");
		digest.reset();
		digest.update(Input.getBytes("utf8"));
		return String.format("%040x", new BigInteger(1, digest.digest()));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SHA1Encrypt";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
