// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Default Mendix uses regeular expressions for replacing string (ReplaceFirst and ReplaceAll). This function just do a search and replace without regex features
 */
public class StringReplaceSimple extends UserAction<java.lang.String>
{
	private final java.lang.String subject;
	private final java.lang.String findString;
	private final java.lang.String replaceString;

	public StringReplaceSimple(
		IContext context,
		java.lang.String _subject,
		java.lang.String _findString,
		java.lang.String _replaceString
	)
	{
		super(context);
		this.subject = _subject;
		this.findString = _findString;
		this.replaceString = _replaceString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return subject.replace(findString, replaceString);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringReplaceSimple";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
