// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class URLContentToFileDocument extends UserAction<java.lang.Void>
{
	private final java.lang.String sourceURL;
	/** @deprecated use fileDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __fileDocument;
	private final system.proxies.FileDocument fileDocument;
	private final java.lang.String fileName;
	private final java.lang.Long connectionTimeout;
	private final java.lang.Long readTimeout;

	public URLContentToFileDocument(
		IContext context,
		java.lang.String _sourceURL,
		IMendixObject _fileDocument,
		java.lang.String _fileName,
		java.lang.Long _connectionTimeout,
		java.lang.Long _readTimeout
	)
	{
		super(context);
		this.sourceURL = _sourceURL;
		this.__fileDocument = _fileDocument;
		this.fileDocument = _fileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _fileDocument);
		this.fileName = _fileName;
		this.connectionTimeout = _connectionTimeout;
		this.readTimeout = _readTimeout;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		final int MAX_REMOTE_FILESIZE = 1024 * 1024 * 200; // 200 MB limit
	    final int BUFFER_SIZE = 8192; // 8 KB chunks

	    // Set default timeouts if not provided
	    int connectTimeoutValue = (connectionTimeout.intValue() > 0) ? connectionTimeout.intValue() : 5000; // 5 seconds
	    int readTimeoutValue = (readTimeout.intValue() > 0 ) ? readTimeout.intValue() : 20000; // 20 seconds

	    
	    HttpURLConnection connection = null;

	    try {
	        URI uri = URI.create(sourceURL);
	        URL fileURL = uri.toURL();
	        connection = (HttpURLConnection) fileURL.openConnection();
	        connection.setConnectTimeout(connectTimeoutValue);
	        connection.setReadTimeout(readTimeoutValue);
	        connection.setRequestProperty("User-Agent", "MendixApp/1.0");
	        connection.connect();

	        int responseCode = connection.getResponseCode();
	        if (responseCode != HttpURLConnection.HTTP_OK) {
	        	throw new com.mendix.systemwideinterfaces.MendixRuntimeException("HTTP error: " + responseCode + " - " + connection.getResponseMessage());
	        }

	        int contentLength = connection.getContentLength();
	        if (contentLength > MAX_REMOTE_FILESIZE) {
	        	throw new com.mendix.systemwideinterfaces.MendixRuntimeException(String.format("File size %d exceeds the max limit of %d", contentLength, MAX_REMOTE_FILESIZE));
	        }

	        try (InputStream inputStream = new BufferedInputStream(connection.getInputStream())) {
	            // Track the total number of bytes read
	            long totalBytesRead = 0;
	            byte[] buffer = new byte[BUFFER_SIZE];

	            // Use Piped Streams to avoid full buffering in memory
	            try (PipedOutputStream pipedOut = new PipedOutputStream();
	                 PipedInputStream pipedIn = new PipedInputStream(pipedOut)) {
	            		
	            	// Start a new thread to write data to Mendix while reading from the URL
	            	Thread writerThread = new Thread(() -> {
	            	    try {
	            	        Core.storeFileDocumentContent(getContext(), fileDocument.getMendixObject(), fileName, pipedIn);
	            	    } catch (Exception e) {
	            	        throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Failed to write document content", e);
	            	    }
	            	});
	            	writerThread.start();

	                int bytesRead;
	                while ((bytesRead = inputStream.read(buffer, 0, BUFFER_SIZE)) != -1) {
	                    totalBytesRead += bytesRead;

	                    if (totalBytesRead > MAX_REMOTE_FILESIZE) {
	                    	throw new com.mendix.systemwideinterfaces.MendixRuntimeException("File exceeds maximum allowed size during download");
	                    }
	                    pipedOut.write(buffer, 0, bytesRead);
	                }
	                pipedOut.flush();
	                pipedOut.close();
	                writerThread.join(); // Ensure all data is written
	            }
	        }
	    } catch (IOException | InterruptedException e) {
	        throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Failed to download and store the file", e);
	    } finally {
	        if (connection != null) {
	            connection.disconnect(); // Ensure connection is released
	        }
	    }

	    return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "URLContentToFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
