// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emixacommons.actions;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.EnumSet;
import java.util.Set;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Calculates the number of workdays between two dates (so the number of days excluding all Saturdays and Sundays).
 */
public class WorkdaysBetween extends UserAction<java.lang.Long>
{
	private final java.util.Date StartDate;
	private final java.util.Date EndDate;

	public WorkdaysBetween(
		IContext context,
		java.util.Date _startDate,
		java.util.Date _endDate
	)
	{
		super(context);
		this.StartDate = _startDate;
		this.EndDate = _endDate;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Avoid null pointer dereference
		if (StartDate == null || EndDate == null) {
		    throw new IllegalArgumentException("StartDate and EndDate must not be provided");
		}		
		LocalDate startDate = StartDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		LocalDate endDate = EndDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		Set<DayOfWeek> weekend = EnumSet.of(DayOfWeek.SATURDAY, DayOfWeek.SUNDAY);
		final long workDaysBetween = startDate.datesUntil(endDate)
		        .filter(d -> !weekend.contains(d.getDayOfWeek()))
		        .count();
		return workDaysBetween;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "WorkdaysBetween";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
