// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import BiometryTools from '@kode-frontend/react-native-biometry-tools';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Gets the type of biometic method of the phone see Enum_BiometricType
 * yarn add @kode-frontend/react-native-biometry-tools if not available
 * @returns {Promise.<string>}
 */
export async function GetBiometricType() {
	// BEGIN USER CODE
    return BiometryTools
      .getSupportedBiometryType()
      .then((biometryType) => {
          return Promise.resolve(biometryType);
          // even if biometry not enrolled
          // biometryType - supported biometry, if biometry not supported then return null
      })
	// END USER CODE
}
