// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import OTP from 'otp-client'

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Will give the ticks remaining to the next iteration of generation of the code for a secret
 * 
 * yarn add otp-client if not available
 * @param {string} secret
 * @returns {Promise.<string>}
 */
export async function GetTimeRemaining(secret) {
	// BEGIN USER CODE
	const otp = new OTP(secret)
	return otp.getTimeUntilNextTick()
	// END USER CODE
}
