// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import ReactNativeHapticFeedback from "react-native-haptic-feedback";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Give the app more native feeling. 
 * Guidelines from Apple: https://developer.apple.com/design/human-interface-guidelines/patterns/playing-haptics/
 * Guidelines from Google: https://m2.material.io/design/platform-guidance/android-haptics.html#usage
 * 
 * yarn add react-native-haptic-feedback
 * @param {"EmixaCommons.Enum_HapticFeedbackMethod.impactHeavy"|"EmixaCommons.Enum_HapticFeedbackMethod.impactMedium"|"EmixaCommons.Enum_HapticFeedbackMethod.impactLight"|"EmixaCommons.Enum_HapticFeedbackMethod.rigid"|"EmixaCommons.Enum_HapticFeedbackMethod.soft"|"EmixaCommons.Enum_HapticFeedbackMethod.notificationSuccess"|"EmixaCommons.Enum_HapticFeedbackMethod.notificationWarning"|"EmixaCommons.Enum_HapticFeedbackMethod.notificationError"} hapticFeedbackMethod - See documentation for guidelines
 * @returns {Promise.<void>}
 */
export async function HapticFeedback(hapticFeedbackMethod) {
	// BEGIN USER CODE
	const options = {
		enableVibrateFallback: true,
		ignoreAndroidSystemSettings: false
	};
	ReactNativeHapticFeedback.trigger(hapticFeedbackMethod, options);

	Haptic.
	return Promise.resolve();
	// END USER CODE
}
