// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { Linking } from "react-native";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Opens the System Settings for your app on the mobile device
 * @returns {Promise.<void>}
 */
export async function OpenSettings() {
	// BEGIN USER CODE
	Linking.openSettings();
	// END USER CODE
}
