// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Easy JS action to reload your page from a nanoflow. If you don't use pageurl's or deeplinks it returns to the homepage
 * @returns {Promise.<void>}
 */
export async function Reload() {
	// BEGIN USER CODE
	mx.reload();
	// END USER CODE
}
